// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har, plus static
// examples for providers that intentionally avoid live-network recordings.
//
// Each entry is a green-path payload for one endpoint. `attachExamples`
// walks the provider tree and hangs the matching entry off each endpoint
// function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.files": {
    "source": "static:xai-files-public-url-filter",
    "payload": {
      "filter": "public_url != null",
      "limit": 10
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST managementApi.v1.collections": {
    "source": "xai/collections-documents-add",
    "payload": {
      "collection_name": "test-collection-for-docs"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST managementApi.v1.collections.documents": {
    "source": "xai/collections-documents-add",
    "payload": {},
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.batches": {
    "source": "xai/batch-get",
    "payload": {
      "name": "Get Test Batch"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.batches.cancel": {
    "source": "xai/batch-cancel",
    "payload": {},
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.batches.requests": {
    "source": "xai/batch-requests",
    "payload": {
      "batch_requests": [
        {
          "batch_request_id": "test_req_0",
          "batch_request": {
            "chat_get_completion": {
              "messages": [
                {
                  "role": "user",
                  "content": "What is 2+2?"
                }
              ],
              "model": "grok-3"
            }
          }
        }
      ]
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.chat.completions": {
    "source": "xai/chat-hello",
    "payload": {
      "model": "grok-3-fast",
      "messages": [
        {
          "role": "user",
          "content": "Say hello in one sentence."
        }
      ],
      "temperature": 0
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.documents.search": {
    "source": "xai/documents-search",
    "payload": {
      "query": "aurora-test-vector",
      "source": {
        "collection_ids": [
          "collection_2afa52a6-f4ce-4f9c-985f-37203c4bbd45"
        ]
      },
      "limit": 5
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.files.publicUrl": {
    "source": "static:xai-files-public-url-create",
    "payload": {
      "expires_after": 86400
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.files.publicUrl.revoke": {
    "source": "static:xai-files-public-url-revoke",
    "payload": {},
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.images.edits": {
    "source": "xai/image-edit-single",
    "payload": {
      "prompt": "Render this as a pencil sketch with detailed shading",
      "model": "grok-imagine-image",
      "image": {
        "url": "<inline image/jpeg data URL — replace with a real URL or upload>",
        "type": "image_url"
      }
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST v1.images.generations": {
    "source": "xai/image-generate-basic",
    "payload": {
      "prompt": "A simple red apple on a white background",
      "model": "grok-imagine-image",
      "n": 1
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST v1.realtime.clientSecrets": {
    "source": "xai/realtime-client-secrets",
    "payload": {
      "model": "grok-2",
      "voice": "echo"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.responses": {
    "source": "xai/responses-crud-create",
    "payload": {
      "model": "grok-4-fast",
      "input": "Hello!"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.responses.compact": {
    "source": "xai/responses-compact",
    "payload": {
      "model": "grok-4-fast",
      "input": [
        {
          "role": "system",
          "content": "You are a concise science tutor."
        },
        {
          "role": "user",
          "content": "What is the Higgs boson?"
        },
        {
          "role": "assistant",
          "content": "The Higgs boson is an elementary particle that gives mass to other particles via the Higgs field."
        },
        {
          "role": "user",
          "content": "How does the Higgs mechanism work?"
        },
        {
          "role": "assistant",
          "content": "Through spontaneous symmetry breaking: the Higgs field has a nonzero vacuum value and particles acquire mass by coupling to it."
        }
      ]
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.tokenizeText": {
    "source": "xai/tokenize-text",
    "payload": {
      "model": "grok-3",
      "text": "Hello world!"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.tts": {
    "source": "xai/tts-welcome",
    "payload": {
      "text": "Welcome to xAI. How can I help you today?",
      "voice_id": "eve",
      "language": "en"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.videos.edits": {
    "source": "xai/video-edit",
    "payload": {
      "model": "grok-imagine-video",
      "prompt": "Give the woman a silver necklace",
      "video": {
        "url": "https://vidgen.x.ai/xai-vidgen-bucket/xai-video-sample.mp4"
      }
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST v1.videos.extensions": {
    "source": "xai/video-extensions-basic",
    "payload": {
      "model": "grok-imagine-video",
      "prompt": "The scene continues with the character walking into a magical forest",
      "video": {
        "url": "https://vidgen.x.ai/xai-vidgen-bucket/xai-video-sample.mp4"
      },
      "duration": 5
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST v1.videos.generations": {
    "source": "xai/video-text-to-video",
    "payload": {
      "prompt": "A white cat with heterochromia eyes walking across a rooftop at golden hour, cinematic drone shot",
      "model": "grok-imagine-video",
      "duration": 10,
      "aspect_ratio": "16:9",
      "resolution": "720p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "PUT managementApi.v1.collections": {
    "source": "xai/collections-put-update",
    "payload": {
      "collection_name": "updated-collection-name"
    },
    "tier": "expensive",
    "runByDefault": false
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
