// Static endpoint cost tier classification.
//
// Every endpoint exposed by the provider packages is mapped to a cost tier
// that the gate system can consult before dispatching a request.
//
// Tier definitions:
//   free      — no marginal cost per request (metadata, listings, status checks)
//   cheap     — very low cost (token counting, small file ops, health checks)
//   expensive — significant cost per request (LLM inference, image/video/audio
//               generation, speech-to-text, embeddings, translation)
//   prohibitive — very high cost per request (fine-tuning, batch training,
//                 large-scale batch inference)

export type CostTier = "free" | "cheap" | "expensive" | "prohibitive";

export interface EndpointCostInfo {
  provider: string;
  dotPath: string;
  method: string;
  tier: CostTier;
  description: string;
  pricingModel: string;
  docsUrl: string;
}

export const ENDPOINT_COSTS: Record<string, EndpointCostInfo> = {
  // ─── alibaba ───
  "alibaba.api.v1.services.aigc.multimodalGeneration.generation": {
    provider: "alibaba",
    dotPath: "api.v1.services.aigc.multimodalGeneration.generation",
    method: "POST",
    tier: "expensive",
    description: "Qwen image generation/editing",
    pricingModel: "Per-request (image generation)",
    docsUrl:
      "https://www.alibabacloud.com/help/en/model-studio/qwen-image-edit",
  },
  "alibaba.api.v1.services.aigc.videoGeneration.videoSynthesis": {
    provider: "alibaba",
    dotPath: "api.v1.services.aigc.videoGeneration.videoSynthesis",
    method: "POST",
    tier: "expensive",
    description: "Qwen video generation",
    pricingModel: "Per-request (video generation)",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },
  "alibaba.api.v1.tasks": {
    provider: "alibaba",
    dotPath: "api.v1.tasks",
    method: "GET",
    tier: "free",
    description: "Check async task status",
    pricingModel: "Free",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },
  "alibaba.api.v1.uploads": {
    provider: "alibaba",
    dotPath: "api.v1.uploads",
    method: "GET",
    tier: "free",
    description: "List uploads",
    pricingModel: "Free",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },
  "alibaba.compatibleMode.v1.chat.completions": {
    provider: "alibaba",
    dotPath: "compatibleMode.v1.chat.completions",
    method: "POST",
    tier: "expensive",
    description: "Chat completions (Qwen models)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },
  "alibaba.compatibleMode.v1.models": {
    provider: "alibaba",
    dotPath: "compatibleMode.v1.models",
    method: "GET",
    tier: "free",
    description: "List available models",
    pricingModel: "Free",
    docsUrl: "https://help.aliyun.com/zh/model-studio",
  },

  // ─── anthropic ───
  "anthropic.v1.files": {
    provider: "anthropic",
    dotPath: "v1.files",
    method: "POST",
    tier: "cheap",
    description: "Upload file for processing",
    pricingModel: "Storage-based (negligible per request)",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.files.content": {
    provider: "anthropic",
    dotPath: "v1.files.content",
    method: "GET",
    tier: "free",
    description: "Download file content",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.files.del": {
    provider: "anthropic",
    dotPath: "v1.files.del",
    method: "DELETE",
    tier: "free",
    description: "Delete file",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.files.list": {
    provider: "anthropic",
    dotPath: "v1.files.list",
    method: "GET",
    tier: "free",
    description: "List files",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.files.retrieve": {
    provider: "anthropic",
    dotPath: "v1.files.retrieve",
    method: "GET",
    tier: "free",
    description: "Retrieve file metadata",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages": {
    provider: "anthropic",
    dotPath: "v1.messages",
    method: "POST",
    tier: "expensive",
    description: "Chat/inference (Claude models)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches": {
    provider: "anthropic",
    dotPath: "v1.messages.batches",
    method: "POST",
    tier: "prohibitive",
    description: "Submit batch inference job",
    pricingModel: "Per-token (batch rate, minimum spend)",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches.cancel": {
    provider: "anthropic",
    dotPath: "v1.messages.batches.cancel",
    method: "POST",
    tier: "cheap",
    description: "Cancel batch job",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches.del": {
    provider: "anthropic",
    dotPath: "v1.messages.batches.del",
    method: "DELETE",
    tier: "free",
    description: "Delete batch job",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches.list": {
    provider: "anthropic",
    dotPath: "v1.messages.batches.list",
    method: "GET",
    tier: "free",
    description: "List batch jobs",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches.results": {
    provider: "anthropic",
    dotPath: "v1.messages.batches.results",
    method: "GET",
    tier: "free",
    description: "Retrieve batch results",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.batches.retrieve": {
    provider: "anthropic",
    dotPath: "v1.messages.batches.retrieve",
    method: "GET",
    tier: "free",
    description: "Get batch job status",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.messages.countTokens": {
    provider: "anthropic",
    dotPath: "v1.messages.countTokens",
    method: "POST",
    tier: "cheap",
    description: "Count tokens in text",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.models.list": {
    provider: "anthropic",
    dotPath: "v1.models.list",
    method: "GET",
    tier: "free",
    description: "List available models",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.models.retrieve": {
    provider: "anthropic",
    dotPath: "v1.models.retrieve",
    method: "GET",
    tier: "free",
    description: "Retrieve model info",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.create": {
    provider: "anthropic",
    dotPath: "v1.skills.create",
    method: "POST",
    tier: "cheap",
    description: "Create skill",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.del": {
    provider: "anthropic",
    dotPath: "v1.skills.del",
    method: "DELETE",
    tier: "free",
    description: "Delete skill",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.list": {
    provider: "anthropic",
    dotPath: "v1.skills.list",
    method: "GET",
    tier: "free",
    description: "List skills",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.retrieve": {
    provider: "anthropic",
    dotPath: "v1.skills.retrieve",
    method: "GET",
    tier: "free",
    description: "Retrieve skill",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.versions.create": {
    provider: "anthropic",
    dotPath: "v1.skills.versions.create",
    method: "POST",
    tier: "cheap",
    description: "Create skill version",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.versions.del": {
    provider: "anthropic",
    dotPath: "v1.skills.versions.del",
    method: "DELETE",
    tier: "free",
    description: "Delete skill version",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },
  "anthropic.v1.skills.versions.list": {
    provider: "anthropic",
    dotPath: "v1.skills.versions.list",
    method: "GET",
    tier: "free",
    description: "List skill versions",
    pricingModel: "Free",
    docsUrl: "https://docs.anthropic.com/en/api",
  },

  // ─── elevenlabs ───
  "elevenlabs.v1.soundGeneration": {
    provider: "elevenlabs",
    dotPath: "v1.soundGeneration",
    method: "POST",
    tier: "expensive",
    description: "Text-to-sound effects",
    pricingModel: "Per-character",
    docsUrl:
      "https://elevenlabs.io/docs/api-reference/text-to-sound-effects/convert",
  },
  "elevenlabs.v1.speechToText": {
    provider: "elevenlabs",
    dotPath: "v1.speechToText",
    method: "POST",
    tier: "expensive",
    description: "Speech-to-text transcription",
    pricingModel: "Per-second",
    docsUrl: "https://elevenlabs.io/docs/api-reference/speech-to-text/convert",
  },

  // ─── fal ───
  "fal.bytedance.seedance2p0.imageToVideo": {
    provider: "fal",
    dotPath: "bytedance.seedance2p0.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Seedance 2.0 image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.bytedance.seedance2p0.textToVideo": {
    provider: "fal",
    dotPath: "bytedance.seedance2p0.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Seedance 2.0 text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.bytedance.seedance2p0.fast.imageToVideo": {
    provider: "fal",
    dotPath: "bytedance.seedance2p0.fast.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Seedance 2.0 fast image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.bytedance.seedance2p0.fast.textToVideo": {
    provider: "fal",
    dotPath: "bytedance.seedance2p0.fast.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Seedance 2.0 fast text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.bytedance.seedream.v5.lite.edit": {
    provider: "fal",
    dotPath: "bytedance.seedream.v5.lite.edit",
    method: "POST",
    tier: "expensive",
    description: "Seedream V5 lite image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.bytedance.seedream.v5.lite.textToImage": {
    provider: "fal",
    dotPath: "bytedance.seedream.v5.lite.textToImage",
    method: "POST",
    tier: "expensive",
    description: "Seedream V5 lite text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.falAi.elevenlabs.speechToText.scribeV2": {
    provider: "fal",
    dotPath: "falAi.elevenlabs.speechToText.scribeV2",
    method: "POST",
    tier: "expensive",
    description: "Scribe V2 speech-to-text",
    pricingModel: "Per-second",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.gptImage1p5": {
    provider: "fal",
    dotPath: "gptImage1p5",
    method: "POST",
    tier: "expensive",
    description: "GPT Image 1.5 text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.gptImage1p5.edit": {
    provider: "fal",
    dotPath: "gptImage1p5.edit",
    method: "POST",
    tier: "expensive",
    description: "GPT Image 1.5 image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.v3.pro.imageToVideo": {
    provider: "fal",
    dotPath: "klingVideo.v3.pro.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video V3 pro image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.v3.pro.textToVideo": {
    provider: "fal",
    dotPath: "klingVideo.v3.pro.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video V3 pro text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.v3.standard.imageToVideo": {
    provider: "fal",
    dotPath: "klingVideo.v3.standard.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video V3 standard image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.v3.standard.textToVideo": {
    provider: "fal",
    dotPath: "klingVideo.v3.standard.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video V3 standard text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.o3p4k.imageToVideo": {
    provider: "fal",
    dotPath: "klingVideo.o3p4k.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video O3 4K image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.o3p4k.referenceToVideo": {
    provider: "fal",
    dotPath: "klingVideo.o3p4k.referenceToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video O3 4K reference-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.klingVideo.o3p4k.textToVideo": {
    provider: "fal",
    dotPath: "klingVideo.o3p4k.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Kling Video O3 4K text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBanana.edit": {
    provider: "fal",
    dotPath: "nanoBanana.edit",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBanana.textToImage": {
    provider: "fal",
    dotPath: "nanoBanana.textToImage",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBanana2.edit": {
    provider: "fal",
    dotPath: "nanoBanana2.edit",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana 2 image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBanana2.textToImage": {
    provider: "fal",
    dotPath: "nanoBanana2.textToImage",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana 2 text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBananaPro.edit": {
    provider: "fal",
    dotPath: "nanoBananaPro.edit",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana Pro image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.nanoBananaPro.textToImage": {
    provider: "fal",
    dotPath: "nanoBananaPro.textToImage",
    method: "POST",
    tier: "expensive",
    description: "NanoBanana Pro text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.qwenImage": {
    provider: "fal",
    dotPath: "qwenImage",
    method: "POST",
    tier: "expensive",
    description: "Qwen image generation",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.qwenImage.edit": {
    provider: "fal",
    dotPath: "qwenImage.edit",
    method: "POST",
    tier: "expensive",
    description: "Qwen image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.sora2.imageToVideo": {
    provider: "fal",
    dotPath: "sora2.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Sora 2 image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.sora2.textToVideo": {
    provider: "fal",
    dotPath: "sora2.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Sora 2 text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models": {
    provider: "fal",
    dotPath: "v1.models",
    method: "GET",
    tier: "free",
    description: "List available models",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models.pricing": {
    provider: "fal",
    dotPath: "v1.models.pricing",
    method: "GET",
    tier: "free",
    description: "Get model pricing",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models.pricing.estimate": {
    provider: "fal",
    dotPath: "v1.models.pricing.estimate",
    method: "GET",
    tier: "free",
    description: "Estimate cost",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models.pricing.estimate#post": {
    provider: "fal",
    dotPath: "v1.models.pricing.estimate",
    method: "POST",
    tier: "free",
    description: "Estimate cost",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models.requests.payloads": {
    provider: "fal",
    dotPath: "v1.models.requests.payloads",
    method: "DELETE",
    tier: "free",
    description: "Delete request payload",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.models.requests.payloads#get": {
    provider: "fal",
    dotPath: "v1.models.requests.payloads",
    method: "GET",
    tier: "free",
    description: "Get request payload",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.queue.submit": {
    provider: "fal",
    dotPath: "v1.queue.submit",
    method: "POST",
    tier: "expensive",
    description: "Submit async generation request",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.serverless.files.uploadLocal": {
    provider: "fal",
    dotPath: "v1.serverless.files.uploadLocal",
    method: "POST",
    tier: "cheap",
    description: "Upload local file",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.serverless.files.uploadUrl": {
    provider: "fal",
    dotPath: "v1.serverless.files.uploadUrl",
    method: "POST",
    tier: "cheap",
    description: "Upload file from URL",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.storage.upload.initiate": {
    provider: "fal",
    dotPath: "storage.upload.initiate",
    method: "POST",
    tier: "cheap",
    description: "Initiate upload",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.storage.upload.initiateMultipart": {
    provider: "fal",
    dotPath: "storage.upload.initiateMultipart",
    method: "POST",
    tier: "cheap",
    description: "Initiate multipart upload",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.storage.upload.completeMultipart": {
    provider: "fal",
    dotPath: "storage.upload.completeMultipart",
    method: "POST",
    tier: "cheap",
    description: "Complete multipart upload",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.serverless.logs": {
    provider: "fal",
    dotPath: "v1.serverless.logs",
    method: "POST",
    tier: "cheap",
    description: "Stream serverless logs",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.v1.workflows": {
    provider: "fal",
    dotPath: "v1.workflows",
    method: "GET",
    tier: "free",
    description: "List workflows",
    pricingModel: "Free",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.veo3p1.imageToVideo": {
    provider: "fal",
    dotPath: "veo3p1.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Veo 3.1 image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.veo3p1.textToVideo": {
    provider: "fal",
    dotPath: "veo3p1.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Veo 3.1 text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.edit": {
    provider: "fal",
    dotPath: "wan.v2p7.edit",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 video editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.textToVideo": {
    provider: "fal",
    dotPath: "wan.v2p7.textToVideo",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 text-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.imageToVideo": {
    provider: "fal",
    dotPath: "wan.v2p7.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.pro.edit": {
    provider: "fal",
    dotPath: "wan.v2p7.pro.edit",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 pro video editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.pro.textToImage": {
    provider: "fal",
    dotPath: "wan.v2p7.pro.textToImage",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 pro text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.wan.v2p7.textToImage": {
    provider: "fal",
    dotPath: "wan.v2p7.textToImage",
    method: "POST",
    tier: "expensive",
    description: "Wan 2.7 text-to-image",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.hunyuan.v3.instructEdit": {
    provider: "fal",
    dotPath: "hunyuan.v3.instructEdit",
    method: "POST",
    tier: "expensive",
    description: "Hunyuan V3 image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineImage": {
    provider: "fal",
    dotPath: "xai.grokImagineImage",
    method: "POST",
    tier: "expensive",
    description: "Grok image generation",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineImage.edit": {
    provider: "fal",
    dotPath: "xai.grokImagineImage.edit",
    method: "POST",
    tier: "expensive",
    description: "Grok image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineVideo.imageToVideo": {
    provider: "fal",
    dotPath: "xai.grokImagineVideo.imageToVideo",
    method: "POST",
    tier: "expensive",
    description: "Grok image-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineVideo.referenceToVideo": {
    provider: "fal",
    dotPath: "xai.grokImagineVideo.referenceToVideo",
    method: "POST",
    tier: "expensive",
    description: "Grok reference-to-video",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineVideo.extendVideo": {
    provider: "fal",
    dotPath: "xai.grokImagineVideo.extendVideo",
    method: "POST",
    tier: "expensive",
    description: "Grok video extension",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },
  "fal.xai.grokImagineVideo.editVideo": {
    provider: "fal",
    dotPath: "xai.grokImagineVideo.editVideo",
    method: "POST",
    tier: "expensive",
    description: "Grok video editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fal.ai",
  },

  // ─── fireworks ───
  "fireworks.inference.v1.chat.completions": {
    provider: "fireworks",
    dotPath: "inference.v1.chat.completions",
    method: "POST",
    tier: "expensive",
    description: "Chat completions",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.completions": {
    provider: "fireworks",
    dotPath: "inference.v1.completions",
    method: "POST",
    tier: "expensive",
    description: "Text completions",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.embeddings": {
    provider: "fireworks",
    dotPath: "inference.v1.embeddings",
    method: "POST",
    tier: "cheap",
    description: "Text embeddings",
    pricingModel: "Per-token (input only)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.messages": {
    provider: "fireworks",
    dotPath: "inference.v1.messages",
    method: "POST",
    tier: "expensive",
    description: "Chat/inference (message format)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.rerank": {
    provider: "fireworks",
    dotPath: "inference.v1.rerank",
    method: "POST",
    tier: "cheap",
    description: "Rerank documents",
    pricingModel: "Per-request (low cost)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.audio.transcriptions": {
    provider: "fireworks",
    dotPath: "inference.v1.audio.transcriptions",
    method: "POST",
    tier: "expensive",
    description: "Speech transcription",
    pricingModel: "Per-second",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.audio.translations": {
    provider: "fireworks",
    dotPath: "inference.v1.audio.translations",
    method: "POST",
    tier: "expensive",
    description: "Speech translation",
    pricingModel: "Per-second",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.audio.batch.transcriptions": {
    provider: "fireworks",
    dotPath: "inference.v1.audio.batch.transcriptions",
    method: "POST",
    tier: "prohibitive",
    description: "Batch speech transcription",
    pricingModel: "Per-second (batch rate)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.audio.batch.translations": {
    provider: "fireworks",
    dotPath: "inference.v1.audio.batch.translations",
    method: "POST",
    tier: "prohibitive",
    description: "Batch speech translation",
    pricingModel: "Per-second (batch rate)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.workflows.getResult": {
    provider: "fireworks",
    dotPath: "inference.v1.workflows.getResult",
    method: "POST",
    tier: "expensive",
    description: "Workflow result",
    pricingModel: "Per-workflow",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.workflows.kontext": {
    provider: "fireworks",
    dotPath: "inference.v1.workflows.kontext",
    method: "POST",
    tier: "expensive",
    description: "Kontext workflow",
    pricingModel: "Per-workflow",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.workflows.textToImage": {
    provider: "fireworks",
    dotPath: "inference.v1.workflows.textToImage",
    method: "POST",
    tier: "expensive",
    description: "Text-to-image workflow",
    pricingModel: "Per-request",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  // All fireworks account management endpoints are free/cheap
  "fireworks.inference.v1.accounts.batchInferenceJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.batchInferenceJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create batch inference job",
    pricingModel: "Per-token (batch rate, minimum spend)",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.dpoJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.dpoJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create DPO job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.dpoJobs.resume": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.dpoJobs.resume",
    method: "POST",
    tier: "prohibitive",
    description: "Resume DPO job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.evaluationJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.evaluationJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create evaluation job",
    pricingModel: "Evaluation cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.evaluators.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.evaluators.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create evaluator",
    pricingModel: "Evaluation cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.reinforcementFineTuningJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.reinforcementFineTuningJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.reinforcementFineTuningJobs.resume": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.reinforcementFineTuningJobs.resume",
    method: "POST",
    tier: "prohibitive",
    description: "Resume fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.rlorTrainerJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.rlorTrainerJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create RLOR trainer job",
    pricingModel: "Training cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.rlorTrainerJobs.executeTrainStep": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.rlorTrainerJobs.executeTrainStep",
    method: "POST",
    tier: "prohibitive",
    description: "Execute RLOR training step",
    pricingModel: "Training cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.rlorTrainerJobs.resume": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.rlorTrainerJobs.resume",
    method: "POST",
    tier: "prohibitive",
    description: "Resume RLOR trainer job",
    pricingModel: "Training cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.supervisedFineTuningJobs.create": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.supervisedFineTuningJobs.create",
    method: "POST",
    tier: "prohibitive",
    description: "Create fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },
  "fireworks.inference.v1.accounts.supervisedFineTuningJobs.resume": {
    provider: "fireworks",
    dotPath: "inference.v1.accounts.supervisedFineTuningJobs.resume",
    method: "POST",
    tier: "prohibitive",
    description: "Resume fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://docs.fireworks.ai/api-reference",
  },

  // ─── free-media-upload ───
  "free-media-upload.catbox.upload": {
    provider: "free-media-upload",
    dotPath: "catbox.upload",
    method: "POST",
    tier: "free",
    description: "Upload to Catbox",
    pricingModel: "Free (donation-supported)",
    docsUrl: "https://catbox.moe/tools.php",
  },
  "free-media-upload.filebin.upload": {
    provider: "free-media-upload",
    dotPath: "filebin.upload",
    method: "POST",
    tier: "free",
    description: "Upload to Filebin",
    pricingModel: "Free",
    docsUrl: "https://filebin.net/",
  },
  "free-media-upload.gofile.upload": {
    provider: "free-media-upload",
    dotPath: "gofile.upload",
    method: "POST",
    tier: "free",
    description: "Upload to Gofile",
    pricingModel: "Free",
    docsUrl: "https://gofile.io/api",
  },
  "free-media-upload.litterbox.upload": {
    provider: "free-media-upload",
    dotPath: "litterbox.upload",
    method: "POST",
    tier: "free",
    description: "Upload to Litterbox",
    pricingModel: "Free",
    docsUrl: "https://litterbox.catbox.moe/",
  },
  "free-media-upload.tempsh.upload": {
    provider: "free-media-upload",
    dotPath: "tempsh.upload",
    method: "POST",
    tier: "free",
    description: "Upload to temp.sh",
    pricingModel: "Free",
    docsUrl: "https://temp.sh/",
  },
  "free-media-upload.tflink.upload": {
    provider: "free-media-upload",
    dotPath: "tflink.upload",
    method: "POST",
    tier: "free",
    description: "Upload to tmpfile.link",
    pricingModel: "Free",
    docsUrl: "https://tmpfile.link/",
  },
  "free-media-upload.tmpfiles.api.v1.upload": {
    provider: "free-media-upload",
    dotPath: "tmpfiles.api.v1.upload",
    method: "POST",
    tier: "free",
    description: "Upload to tmpfiles.org",
    pricingModel: "Free",
    docsUrl: "https://tmpfiles.org/",
  },
  "free-media-upload.uguu.upload": {
    provider: "free-media-upload",
    dotPath: "uguu.upload",
    method: "POST",
    tier: "free",
    description: "Upload to uguu.se",
    pricingModel: "Free",
    docsUrl: "https://uguu.se/",
  },

  // ─── kie ───
  "kie.api.fileBase64Upload": {
    provider: "kie",
    dotPath: "api.fileBase64Upload",
    method: "POST",
    tier: "cheap",
    description: "Upload file (base64)",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.fileStreamUpload": {
    provider: "kie",
    dotPath: "api.fileStreamUpload",
    method: "POST",
    tier: "cheap",
    description: "Upload file (stream)",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.fileUrlUpload": {
    provider: "kie",
    dotPath: "api.fileUrlUpload",
    method: "POST",
    tier: "cheap",
    description: "Upload file from URL",
    pricingModel: "Storage-based",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.chat.credit": {
    provider: "kie",
    dotPath: "api.v1.chat.credit",
    method: "GET",
    tier: "free",
    description: "Check credits",
    pricingModel: "Free",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.common.downloadUrl": {
    provider: "kie",
    dotPath: "api.v1.common.downloadUrl",
    method: "POST",
    tier: "free",
    description: "Get download URL",
    pricingModel: "Free",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.generate": {
    provider: "kie",
    dotPath: "api.v1.generate",
    method: "POST",
    tier: "expensive",
    description: "Generate music (Suno)",
    pricingModel: "Per-song",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.generate.addInstrumental": {
    provider: "kie",
    dotPath: "api.v1.generate.addInstrumental",
    method: "POST",
    tier: "expensive",
    description: "Add instrumental to song",
    pricingModel: "Per-song",
    docsUrl: "https://docs.kie.ai/suno-api/add-instrumental",
  },
  "kie.api.v1.generate.addVocals": {
    provider: "kie",
    dotPath: "api.v1.generate.addVocals",
    method: "POST",
    tier: "expensive",
    description: "Add vocals to song",
    pricingModel: "Per-song",
    docsUrl: "https://docs.kie.ai/suno-api/add-vocals",
  },
  "kie.api.v1.generate.mashup": {
    provider: "kie",
    dotPath: "api.v1.generate.mashup",
    method: "POST",
    tier: "expensive",
    description: "Generate mashup",
    pricingModel: "Per-song",
    docsUrl: "https://docs.kie.ai/suno-api/generate-mashup",
  },
  "kie.api.v1.generate.replaceSection": {
    provider: "kie",
    dotPath: "api.v1.generate.replaceSection",
    method: "POST",
    tier: "expensive",
    description: "Replace song section",
    pricingModel: "Per-song",
    docsUrl: "https://docs.kie.ai/suno-api/replace-section",
  },
  "kie.api.v1.generate.sounds": {
    provider: "kie",
    dotPath: "api.v1.generate.sounds",
    method: "POST",
    tier: "expensive",
    description: "Generate sound effects",
    pricingModel: "Per-sound",
    docsUrl: "https://docs.kie.ai/suno-api/generate-sounds",
  },
  "kie.api.v1.jobs.createTask": {
    provider: "kie",
    dotPath: "api.v1.jobs.createTask",
    method: "POST",
    tier: "cheap",
    description: "Create async task",
    pricingModel: "Free",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.jobs.recordInfo": {
    provider: "kie",
    dotPath: "api.v1.jobs.recordInfo",
    method: "GET",
    tier: "free",
    description: "Get task status",
    pricingModel: "Free",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.veo.extend": {
    provider: "kie",
    dotPath: "api.v1.veo.extend",
    method: "POST",
    tier: "expensive",
    description: "Extend video (Veo)",
    pricingModel: "Per-request",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.api.v1.veo.generate": {
    provider: "kie",
    dotPath: "api.v1.veo.generate",
    method: "POST",
    tier: "expensive",
    description: "Generate video (Veo)",
    pricingModel: "Per-request",
    docsUrl: "https://docs.kie.ai",
  },
  "kie.claude.v1.messages": {
    provider: "kie",
    dotPath: "claude.v1.messages",
    method: "POST",
    tier: "expensive",
    description: "Chat (Claude via Kie)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.kie.ai",
  },

  // ─── kimicoding ───
  "kimicoding.coding.v1.countTokens": {
    provider: "kimicoding",
    dotPath: "coding.v1.countTokens",
    method: "POST",
    tier: "cheap",
    description: "Count tokens",
    pricingModel: "Free",
    docsUrl: "https://platform.moonshot.ai/docs",
  },
  "kimicoding.coding.v1.embeddings": {
    provider: "kimicoding",
    dotPath: "coding.v1.embeddings",
    method: "POST",
    tier: "cheap",
    description: "Text embeddings",
    pricingModel: "Per-token (input only)",
    docsUrl: "https://platform.moonshot.ai/docs",
  },
  "kimicoding.coding.v1.messages": {
    provider: "kimicoding",
    dotPath: "coding.v1.messages",
    method: "POST",
    tier: "expensive",
    description: "Chat completions (Kimi)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://platform.moonshot.ai/docs",
  },
  "kimicoding.coding.v1.models": {
    provider: "kimicoding",
    dotPath: "coding.v1.models",
    method: "GET",
    tier: "free",
    description: "List models",
    pricingModel: "Free",
    docsUrl: "https://platform.moonshot.ai/docs",
  },

  // ─── openai ───
  "openai.v1.audio.speech": {
    provider: "openai",
    dotPath: "v1.audio.speech",
    method: "POST",
    tier: "expensive",
    description: "Text-to-speech",
    pricingModel: "Per-character",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.audio.transcriptions": {
    provider: "openai",
    dotPath: "v1.audio.transcriptions",
    method: "POST",
    tier: "expensive",
    description: "Speech-to-text",
    pricingModel: "Per-minute",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.audio.translations": {
    provider: "openai",
    dotPath: "v1.audio.translations",
    method: "POST",
    tier: "expensive",
    description: "Speech translation",
    pricingModel: "Per-minute",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.batches": {
    provider: "openai",
    dotPath: "v1.batches",
    method: "GET",
    tier: "free",
    description: "Get batch info",
    pricingModel: "Free",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.batches#create": {
    provider: "openai",
    dotPath: "v1.batches",
    method: "POST",
    tier: "prohibitive",
    description: "Create batch job",
    pricingModel: "Per-token (batch rate, minimum spend)",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.batches.cancel": {
    provider: "openai",
    dotPath: "v1.batches.cancel",
    method: "POST",
    tier: "cheap",
    description: "Cancel batch job",
    pricingModel: "Free",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.chat.completions": {
    provider: "openai",
    dotPath: "v1.chat.completions",
    method: "POST",
    tier: "expensive",
    description: "Chat completions",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.embeddings": {
    provider: "openai",
    dotPath: "v1.embeddings",
    method: "POST",
    tier: "cheap",
    description: "Text embeddings",
    pricingModel: "Per-token (input only)",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.files": {
    provider: "openai",
    dotPath: "v1.files",
    method: "POST",
    tier: "cheap",
    description: "Upload file",
    pricingModel: "Storage-based",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.fineTuning.jobs#create": {
    provider: "openai",
    dotPath: "v1.fineTuning.jobs",
    method: "POST",
    tier: "prohibitive",
    description: "Create fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.fineTuning.jobs.resume": {
    provider: "openai",
    dotPath: "v1.fineTuning.jobs.resume",
    method: "POST",
    tier: "prohibitive",
    description: "Resume fine-tuning job",
    pricingModel: "Fine-tuning cost",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.images.edits": {
    provider: "openai",
    dotPath: "v1.images.edits",
    method: "POST",
    tier: "expensive",
    description: "Image editing",
    pricingModel: "Per-image",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.images.generations": {
    provider: "openai",
    dotPath: "v1.images.generations",
    method: "POST",
    tier: "expensive",
    description: "Image generation",
    pricingModel: "Per-image",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.images.variations": {
    provider: "openai",
    dotPath: "v1.images.variations",
    method: "POST",
    tier: "expensive",
    description: "Image variations",
    pricingModel: "Per-image",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.moderations": {
    provider: "openai",
    dotPath: "v1.moderations",
    method: "POST",
    tier: "cheap",
    description: "Content moderation",
    pricingModel: "Per-request (low cost)",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.responses": {
    provider: "openai",
    dotPath: "v1.responses",
    method: "POST",
    tier: "expensive",
    description: "Response API",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  "openai.v1.responses.inputTokens": {
    provider: "openai",
    dotPath: "v1.responses.inputTokens",
    method: "POST",
    tier: "cheap",
    description: "Count input tokens",
    pricingModel: "Free",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },

  // ─── xai ───
  "xai.v1.batches": {
    provider: "xai",
    dotPath: "v1.batches",
    method: "GET",
    tier: "free",
    description: "Get batch info",
    pricingModel: "Free",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.batches#create": {
    provider: "xai",
    dotPath: "v1.batches",
    method: "POST",
    tier: "prohibitive",
    description: "Create batch job",
    pricingModel: "Per-token (batch rate)",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.chat.completions": {
    provider: "xai",
    dotPath: "v1.chat.completions",
    method: "POST",
    tier: "expensive",
    description: "Chat completions (Grok)",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.customVoices": {
    provider: "xai",
    dotPath: "v1.customVoices",
    method: "POST",
    tier: "expensive",
    description: "Create custom voice",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.images.edits": {
    provider: "xai",
    dotPath: "v1.images.edits",
    method: "POST",
    tier: "expensive",
    description: "Image editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.images.generations": {
    provider: "xai",
    dotPath: "v1.images.generations",
    method: "POST",
    tier: "expensive",
    description: "Image generation",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.responses": {
    provider: "xai",
    dotPath: "v1.responses",
    method: "POST",
    tier: "expensive",
    description: "Response API",
    pricingModel: "Per-token (input/output)",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.stt": {
    provider: "xai",
    dotPath: "v1.stt",
    method: "POST",
    tier: "expensive",
    description: "Speech-to-text",
    pricingModel: "Per-second",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.tts": {
    provider: "xai",
    dotPath: "v1.tts",
    method: "POST",
    tier: "expensive",
    description: "Text-to-speech",
    pricingModel: "Per-character",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.videos.edits": {
    provider: "xai",
    dotPath: "v1.videos.edits",
    method: "POST",
    tier: "expensive",
    description: "Video editing",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.videos.extensions": {
    provider: "xai",
    dotPath: "v1.videos.extensions",
    method: "POST",
    tier: "expensive",
    description: "Video extension",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.videos.generations": {
    provider: "xai",
    dotPath: "v1.videos.generations",
    method: "POST",
    tier: "expensive",
    description: "Video generation",
    pricingModel: "Per-request",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.tokenizeText": {
    provider: "xai",
    dotPath: "v1.tokenizeText",
    method: "POST",
    tier: "cheap",
    description: "Tokenize text",
    pricingModel: "Free",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },
  "xai.v1.documents.search": {
    provider: "xai",
    dotPath: "v1.documents.search",
    method: "POST",
    tier: "cheap",
    description: "Search documents",
    pricingModel: "Per-request (low cost)",
    docsUrl: "https://docs.x.ai/docs/api-reference",
  },

  // ─── x ───
  "x.v2.tweets": {
    provider: "x",
    dotPath: "v2.tweets",
    method: "POST",
    tier: "free",
    description: "Create tweet",
    pricingModel: "Free",
    docsUrl: "https://docs.x.com/x-api/posts/create-post",
  },

  // ─── meta ───
  "meta.v25.media": {
    provider: "meta",
    dotPath: "v25.media",
    method: "POST",
    tier: "free",
    description: "Create Instagram media",
    pricingModel: "Free",
    docsUrl:
      "https://developers.facebook.com/docs/instagram-platform/instagram-graph-api/reference/ig-user/media/",
  },
  "meta.v25.mediaPublish": {
    provider: "meta",
    dotPath: "v25.mediaPublish",
    method: "POST",
    tier: "free",
    description: "Publish Instagram media",
    pricingModel: "Free",
    docsUrl:
      "https://developers.facebook.com/docs/instagram-platform/instagram-graph-api/reference/ig-user/media_publish/",
  },

  // ─── youtube ───
  "youtube.videos.insert": {
    provider: "youtube",
    dotPath: "videos.insert",
    method: "POST",
    tier: "free",
    description: "Upload video",
    pricingModel: "Free (quota-based)",
    docsUrl: "https://developers.google.com/youtube/v3/docs/videos/insert",
  },
};

// ─── Helper functions ───

export function getEndpointCost(key: string): EndpointCostInfo | undefined {
  return ENDPOINT_COSTS[key];
}

export function getTier(key: string): CostTier | undefined {
  return ENDPOINT_COSTS[key]?.tier;
}

export function isExpensiveOrWorse(key: string): boolean {
  const tier = getTier(key);
  return tier === "expensive" || tier === "prohibitive";
}

export function isProhibitive(key: string): boolean {
  return getTier(key) === "prohibitive";
}

export function listByTier(tier: CostTier): EndpointCostInfo[] {
  return Object.values(ENDPOINT_COSTS).filter((e) => e.tier === tier);
}

export function listByProvider(provider: string): EndpointCostInfo[] {
  return Object.values(ENDPOINT_COSTS).filter((e) => e.provider === provider);
}

export function countByTier(): Record<CostTier, number> {
  const counts: Record<CostTier, number> = {
    free: 0,
    cheap: 0,
    expensive: 0,
    prohibitive: 0,
  };
  for (const entry of Object.values(ENDPOINT_COSTS)) {
    counts[entry.tier]++;
  }
  return counts;
}
