export { createS3 } from "./s3";
export { S3Error } from "./types";
export { withFallback, withRetry } from "./middleware";

export type { FallbackOptions, RetryOptions } from "./middleware";

export type {
  S3AbortMultipartUploadMethod,
  S3AbortMultipartUploadRequest,
  S3AbortMultipartUploadResponse,
  S3Bucket,
  S3BucketsNamespace,
  S3ChecksumFields,
  S3CommonPrefix,
  S3CompleteMultipartUploadMethod,
  S3CompleteMultipartUploadRequest,
  S3CompleteMultipartUploadResponse,
  S3CopyObjectMethod,
  S3CopyObjectRequest,
  S3CopyObjectResponse,
  S3CreateBucketMethod,
  S3CreateBucketRequest,
  S3CreateBucketResponse,
  S3CreateMultipartUploadMethod,
  S3CreateMultipartUploadRequest,
  S3CreateMultipartUploadResponse,
  S3DeleteBucketMethod,
  S3DeleteBucketResponse,
  S3DeleteObjectMethod,
  S3DeleteObjectRequest,
  S3DeleteObjectResponse,
  S3DeleteObjectTaggingMethod,
  S3DeleteObjectTaggingResponse,
  S3GetBucketLocationMethod,
  S3GetBucketLocationResponse,
  S3GetObjectMethod,
  S3GetObjectRequest,
  S3GetObjectResponse,
  S3GetObjectTaggingMethod,
  S3GetObjectTaggingResponse,
  S3HeadBucketMethod,
  S3HeadBucketResponse,
  S3HeadObjectMethod,
  S3HeadObjectRequest,
  S3HeadObjectResponse,
  S3ListBucketsMethod,
  S3ListBucketsRequest,
  S3ListBucketsResponse,
  S3ListMultipartUploadsMethod,
  S3ListMultipartUploadsRequest,
  S3ListMultipartUploadsResponse,
  S3ListObjectsV2Method,
  S3ListObjectsV2Request,
  S3ListObjectsV2Response,
  S3ListPartsMethod,
  S3ListPartsRequest,
  S3ListPartsResponse,
  S3MultipartUploadPart,
  S3MultipartUploadSummary,
  S3ObjectHeaders,
  S3ObjectSummary,
  S3ObjectTag,
  S3ObjectTaggingRequest,
  S3ObjectsNamespace,
  S3Options,
  S3Owner,
  S3Provider,
  S3PutObjectTaggingMethod,
  S3PutObjectTaggingRequest,
  S3PutObjectTaggingResponse,
  S3PutObjectMethod,
  S3PutObjectRequest,
  S3PutObjectResponse,
  S3UploadPartCopyMethod,
  S3UploadPartCopyRequest,
  S3UploadPartCopyResponse,
  S3UploadPartMethod,
  S3UploadPartRequest,
  S3UploadPartResponse,
} from "./types";

export {
  S3AbortMultipartUploadRequestSchema,
  S3BucketRequestSchema,
  S3CompleteMultipartUploadRequestSchema,
  S3CopyObjectRequestSchema,
  S3CreateBucketRequestSchema,
  S3CreateMultipartUploadRequestSchema,
  S3DeleteObjectRequestSchema,
  S3GetObjectRequestSchema,
  S3HeadObjectRequestSchema,
  S3ListBucketsRequestSchema,
  S3ListMultipartUploadsRequestSchema,
  S3ListObjectsV2RequestSchema,
  S3ListPartsRequestSchema,
  S3ObjectTaggingRequestSchema,
  S3OptionsSchema,
  S3PutObjectTaggingRequestSchema,
  S3PutObjectRequestSchema,
  S3UploadPartCopyRequestSchema,
  S3UploadPartRequestSchema,
} from "./zod";
