// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET clob.book": {
    "source": "polymarket/clob-book",
    "payload": {
      "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.lastTradePrice": {
    "source": "polymarket/clob-last-trade-price",
    "payload": {
      "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.markets": {
    "source": "polymarket/gamma-markets-list",
    "payload": {
      "limit": 2,
      "closed": false
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.midpoint": {
    "source": "polymarket/clob-midpoint",
    "payload": {
      "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.price": {
    "source": "polymarket/clob-price",
    "payload": {
      "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025",
      "side": "BUY"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.pricesHistory": {
    "source": "polymarket/clob-prices-history-interval",
    "payload": {
      "market": "78433024518676680431174478322854148606578065650008220678402966840627347604025",
      "interval": "1h"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET clob.spread": {
    "source": "polymarket/clob-spread",
    "payload": {
      "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.activity": {
    "source": "polymarket/data-activity",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 3
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.activity.combos": {
    "source": "polymarket/data-combo-activity",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.builders.leaderboard": {
    "source": "polymarket/data-builders-leaderboard",
    "payload": {
      "timePeriod": "DAY",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.builders.volume": {
    "source": "polymarket/data-builders-volume",
    "payload": {
      "timePeriod": "DAY"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.closedPositions": {
    "source": "polymarket/data-closed-positions",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.holders": {
    "source": "polymarket/data-holders",
    "payload": {
      "market": "0x384e2707bbb95da4bfa6f330fe7d5ccbec1c0a85e20be900cbf599987588e1a4",
      "limit": 3
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.leaderboard": {
    "source": "polymarket/data-leaderboard",
    "payload": {
      "timePeriod": "DAY",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.liveVolume": {
    "source": "polymarket/data-live-volume",
    "payload": {
      "id": 16167
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.marketPositions": {
    "source": "polymarket/data-market-positions",
    "payload": {
      "market": "0x384e2707bbb95da4bfa6f330fe7d5ccbec1c0a85e20be900cbf599987588e1a4",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.positions": {
    "source": "polymarket/data-positions",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 2
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.positions.combos": {
    "source": "polymarket/data-combo-positions",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.traded": {
    "source": "polymarket/data-traded",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.trades": {
    "source": "polymarket/data-trades",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e",
      "limit": 3
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET data.value": {
    "source": "polymarket/data-value",
    "payload": {
      "user": "0xf9ac4c4ef54ee6010a28299ec1d616b63bf7806e"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET gamma.comments": {
    "source": "polymarket/gamma-comments-list",
    "payload": {
      "parent_entity_type": "Event",
      "parent_entity_id": 16167,
      "limit": 2
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET gamma.events": {
    "source": "polymarket/gamma-events-list",
    "payload": {
      "limit": 2,
      "closed": false
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET gamma.search": {
    "source": "polymarket/gamma-search",
    "payload": {
      "q": "trump",
      "limit_per_type": 2
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET gamma.series": {
    "source": "polymarket/gamma-series-list",
    "payload": {
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET gamma.tags": {
    "source": "polymarket/gamma-tags-list",
    "payload": {
      "limit": 2
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.batchPricesHistory": {
    "source": "polymarket/clob-batch-prices-history",
    "payload": {
      "markets": [
        "78433024518676680431174478322854148606578065650008220678402966840627347604025",
        "50346565575310273995396997144874891836871065259829083228393044602519086496922"
      ],
      "interval": "1h"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.books": {
    "source": "polymarket/clob-books-batch",
    "payload": [
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
      },
      {
        "token_id": "50346565575310273995396997144874891836871065259829083228393044602519086496922"
      }
    ],
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.lastTradesPrices": {
    "source": "polymarket/clob-last-trades-prices-batch",
    "payload": [
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
      }
    ],
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.midpoints": {
    "source": "polymarket/clob-midpoints-batch",
    "payload": [
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
      },
      {
        "token_id": "50346565575310273995396997144874891836871065259829083228393044602519086496922"
      }
    ],
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.prices": {
    "source": "polymarket/clob-prices-batch",
    "payload": [
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025",
        "side": "BUY"
      },
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025",
        "side": "SELL"
      }
    ],
    "tier": "cheap",
    "runByDefault": true
  },
  "POST clob.spreads": {
    "source": "polymarket/clob-spreads-batch",
    "payload": [
      {
        "token_id": "78433024518676680431174478322854148606578065650008220678402966840627347604025"
      },
      {
        "token_id": "50346565575310273995396997144874891836871065259829083228393044602519086496922"
      }
    ],
    "tier": "cheap",
    "runByDefault": true
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
