export { createTheSportsDB } from "./thesportsdb";
export { TheSportsDBError } from "./types";

export {
  TheSportsDBEquipmentLookupRequestSchema,
  TheSportsDBLeagueLookupRequestSchema,
  TheSportsDBOptionsSchema,
  TheSportsDBSearchEventsRequestSchema,
  TheSportsDBSearchFilenameRequestSchema,
  TheSportsDBSearchPlayersRequestSchema,
  TheSportsDBSearchTeamsRequestSchema,
  TheSportsDBSearchVenuesRequestSchema,
  TheSportsDBTableLookupRequestSchema,
  TheSportsDBTeamLookupRequestSchema,
  TheSportsDBVenueLookupRequestSchema,
  type TheSportsDBOptions,
} from "./zod";

export type {
  TheSportsDBAllCountriesMethod,
  TheSportsDBAllLeaguesMethod,
  TheSportsDBAllSportsMethod,
  TheSportsDBCountriesResponse,
  TheSportsDBCountry,
  TheSportsDBEndpointMethod,
  TheSportsDBEvent,
  TheSportsDBEventsResponse,
  TheSportsDBEquipment,
  TheSportsDBEquipmentLookupMethod,
  TheSportsDBEquipmentLookupRequest,
  TheSportsDBEquipmentLookupResponse,
  TheSportsDBField,
  TheSportsDBFilenameSearchResponse,
  TheSportsDBGetNamespace,
  TheSportsDBId,
  TheSportsDBLeague,
  TheSportsDBLeagueLookupMethod,
  TheSportsDBLeagueLookupRequest,
  TheSportsDBLeagueLookupResponse,
  TheSportsDBLeaguesResponse,
  TheSportsDBPlayer,
  TheSportsDBPlayersResponse,
  TheSportsDBProvider,
  TheSportsDBRecord,
  TheSportsDBSearchEventsMethod,
  TheSportsDBSearchEventsRequest,
  TheSportsDBSearchFilenameMethod,
  TheSportsDBSearchFilenameRequest,
  TheSportsDBSearchPlayersMethod,
  TheSportsDBSearchPlayersRequest,
  TheSportsDBSearchTeamsMethod,
  TheSportsDBSearchTeamsRequest,
  TheSportsDBSearchVenuesMethod,
  TheSportsDBSearchVenuesRequest,
  TheSportsDBSport,
  TheSportsDBSportsResponse,
  TheSportsDBTableLookupMethod,
  TheSportsDBTableLookupRequest,
  TheSportsDBTableLookupResponse,
  TheSportsDBTableRow,
  TheSportsDBTeam,
  TheSportsDBTeamLookupMethod,
  TheSportsDBTeamLookupRequest,
  TheSportsDBTeamLookupResponse,
  TheSportsDBTeamsResponse,
  TheSportsDBV1LookupNamespace,
  TheSportsDBV1Namespace,
  TheSportsDBVenue,
  TheSportsDBVenueLookupMethod,
  TheSportsDBVenueLookupRequest,
  TheSportsDBVenueLookupResponse,
  TheSportsDBVenuesResponse,
} from "./types";
