export { createTheSportsDB } from "./thesportsdb";
export { TheSportsDBError } from "./types";

export {
  TheSportsDBEquipmentLookupRequestSchema,
  TheSportsDBLeagueLookupRequestSchema,
  TheSportsDBOptionsSchema,
  TheSportsDBTableLookupRequestSchema,
  TheSportsDBTeamLookupRequestSchema,
  TheSportsDBVenueLookupRequestSchema,
  type TheSportsDBOptions,
} from "./zod";

export type {
  TheSportsDBAllCountriesMethod,
  TheSportsDBAllLeaguesMethod,
  TheSportsDBAllSportsMethod,
  TheSportsDBCountriesResponse,
  TheSportsDBCountry,
  TheSportsDBEndpointMethod,
  TheSportsDBEquipment,
  TheSportsDBEquipmentLookupMethod,
  TheSportsDBEquipmentLookupRequest,
  TheSportsDBEquipmentLookupResponse,
  TheSportsDBField,
  TheSportsDBGetNamespace,
  TheSportsDBId,
  TheSportsDBLeague,
  TheSportsDBLeagueLookupMethod,
  TheSportsDBLeagueLookupRequest,
  TheSportsDBLeagueLookupResponse,
  TheSportsDBLeaguesResponse,
  TheSportsDBProvider,
  TheSportsDBRecord,
  TheSportsDBSport,
  TheSportsDBSportsResponse,
  TheSportsDBTableLookupMethod,
  TheSportsDBTableLookupRequest,
  TheSportsDBTableLookupResponse,
  TheSportsDBTableRow,
  TheSportsDBTeam,
  TheSportsDBTeamLookupMethod,
  TheSportsDBTeamLookupRequest,
  TheSportsDBTeamLookupResponse,
  TheSportsDBV1LookupNamespace,
  TheSportsDBV1Namespace,
  TheSportsDBVenue,
  TheSportsDBVenueLookupMethod,
  TheSportsDBVenueLookupRequest,
  TheSportsDBVenueLookupResponse,
} from "./types";
