import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      ".omp/**",
      ".gc/**",
      ".opencode/**",
      "worktrees/**",
      // Auto-generated by `pnpm run gen:examples`.
      "packages/provider/*/src/example.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      sourceType: "module",
      globals: globals.node,
    },
    rules: {
      "no-console": "off",
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  // Formatting is enforced separately via `pnpm run format:check`
  // (prettier --check). Running Prettier as an ESLint rule was the dominant
  // lint cost, so we drop the plugin and only disable ESLint's stylistic rules
  // that would conflict with Prettier. Keep this entry LAST.
  eslintConfigPrettier,
];
