import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/coverage/**",
      ".omp/**",
      ".gc/**",
      ".opencode/**",
      "worktrees/**",
      // Gas City molecule scratch — untracked build artifacts and per-bead work
      // dirs written into shared agent home worktrees, absent on clean CI. The
      // top-level `worktrees/**` above does not reach nested per-bead worktrees,
      // so `**/worktrees/**` covers those at any depth (e.g.
      // `ac-*/worktrees/*/.omp/hooks/gc-hook.ts`).
      "plans/**",
      "ac-*/**",
      "**/worktrees/**",
      // Auto-generated by `pnpm run gen:examples`.
      "packages/provider/*/src/example.ts",
      // Gas City / agent tooling scratch in shared rig checkouts — untracked,
      // absent on clean CI. Flat-config `ignores` are not implicitly
      // recursive, so the nested checkout copy needs a `**/` prefix: the
      // `.omp/**` entry above does not reach `apicity/.omp/hooks/gc-hook.ts`,
      // today's only lint error. `apicity/**` covers the rest of that nested
      // copy if the tool syncs more into it.
      "**/.omp/**",
      "apicity/**",
      ".codex/**",
      ".agents/skills/*.*/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      sourceType: "module",
      globals: globals.node,
    },
    rules: {
      "no-console": "off",
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  // Formatting is enforced separately via `pnpm run format:check`
  // (prettier --check). Running Prettier as an ESLint rule was the dominant
  // lint cost, so we drop the plugin and only disable ESLint's stylistic rules
  // that would conflict with Prettier. Keep this entry LAST.
  eslintConfigPrettier,
];
