// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.audioIsolation.history.list": {
    "source": "elevenlabs/audio-isolation",
    "payload": {
      "page_size": 1000
    }
  },
  "GET v1.convai.agentTesting.list": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "page_size": 30,
      "parent_folder_id": "tfld_4801kw9vb0v1ewp9h2c1dc7893yv",
      "types": [
        "llm",
        "folder"
      ],
      "sort_mode": "folders_first",
      "sharing_mode": "all"
    }
  },
  "GET v1.convai.agents.list": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "page_size": 30
    }
  },
  "GET v1.convai.conversation.getSignedUrl": {
    "source": "elevenlabs/convai-conversations",
    "payload": {
      "agent_id": "agent_7701kvak8r92e03921wqazqbb5kc"
    }
  },
  "GET v1.convai.conversations.list": {
    "source": "elevenlabs/convai-conversations",
    "payload": {
      "page_size": 3
    }
  },
  "GET v1.convai.knowledgeBase.list": {
    "source": "elevenlabs/convai-knowledge-base",
    "payload": {
      "page_size": 30
    }
  },
  "GET v1.convai.testInvocations.list": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "agent_id": "agent_4801kw9vazcbedyt8wgke5n8z0x6",
      "page_size": 30
    }
  },
  "GET v1.convai.tools.list": {
    "source": "elevenlabs/convai-tools",
    "payload": {
      "page_size": 30
    }
  },
  "GET v1.dubbing.list": {
    "source": "elevenlabs/dubbing",
    "payload": {
      "page_size": 50
    }
  },
  "GET v1.sharedVoices": {
    "source": "elevenlabs/voice-library",
    "payload": {
      "page_size": 3
    }
  },
  "GET v2.voices": {
    "source": "elevenlabs/voices",
    "payload": {
      "page_size": 1,
      "voice_type": "default",
      "include_total_count": true
    }
  },
  "PATCH v1.convai.agentTesting.folders.update": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "name": "Apicity route test folder updated"
    }
  },
  "PATCH v1.convai.agents.update": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "name": "Apicity agents route test (updated)"
    }
  },
  "PATCH v1.convai.phoneNumbers.update": {
    "source": "elevenlabs/convai-phone-numbers",
    "payload": {
      "label": "Apicity phone-number route test (updated)"
    }
  },
  "PATCH v1.convai.tools.update": {
    "source": "elevenlabs/convai-tools",
    "payload": {
      "tool_config": {
        "type": "webhook",
        "name": "apicity_route_test_tool",
        "description": "Apicity tools route test webhook (updated).",
        "api_schema": {
          "url": "https://example.com/apicity/route-test",
          "method": "GET"
        }
      }
    }
  },
  "PATCH v1.productions.orders.update": {
    "source": "elevenlabs/productions-orders",
    "payload": {
      "request": {
        "name": "Spanish Dubs"
      }
    }
  },
  "PATCH v1.speechEngine.update": {
    "source": "elevenlabs/speech-engine",
    "payload": {
      "name": "Updated Speech Engine"
    }
  },
  "POST v1.audioNative.content.fromUrl": {
    "source": "elevenlabs/audio-native-content-url",
    "payload": {
      "url": "https://elevenlabs.io/blog",
      "title": "Apicity Audio Native URL",
      "author": "Apicity"
    }
  },
  "POST v1.convai.agentTesting.bulkMove": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "entity_ids": [
        "test_7801kw9vb11jfs0vfpn8x9148vmn"
      ],
      "move_to": "tfld_4801kw9vb0v1ewp9h2c1dc7893yv"
    }
  },
  "POST v1.convai.agentTesting.create": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "name": "Apicity route response test",
      "type": "llm",
      "chat_history": [
        {
          "role": "user",
          "message": "Say hello from Apicity in one short sentence.",
          "time_in_call_secs": 0
        }
      ],
      "success_condition": "The agent responds with a short greeting that mentions Apicity."
    }
  },
  "POST v1.convai.agentTesting.folders.create": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "name": "Apicity route test folder"
    }
  },
  "POST v1.convai.agentTesting.summaries": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "test_ids": [
        "test_7801kw9vb11jfs0vfpn8x9148vmn"
      ]
    }
  },
  "POST v1.convai.agents.create": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "name": "Apicity agents route test",
      "conversation_config": {
        "agent": {
          "prompt": {
            "prompt": "You are a helpful Apicity route-test assistant."
          },
          "first_message": "Hello from Apicity.",
          "language": "en"
        }
      },
      "tags": [
        "apicity-test"
      ]
    }
  },
  "POST v1.convai.agents.runTests": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "tests": [
        {
          "test_id": "test_7801kw9vb11jfs0vfpn8x9148vmn"
        }
      ],
      "repeat_count": 1
    }
  },
  "POST v1.convai.knowledgeBase.text": {
    "source": "elevenlabs/convai-knowledge-base",
    "payload": {
      "name": "Apicity KB route test (text)",
      "text": "Apicity is a TypeScript monorepo of standalone API provider packages."
    }
  },
  "POST v1.convai.knowledgeBase.url": {
    "source": "elevenlabs/convai-knowledge-base",
    "payload": {
      "name": "Apicity KB route test (url)",
      "url": "https://elevenlabs.io/docs/api-reference/introduction"
    }
  },
  "POST v1.convai.phoneNumbers.create": {
    "source": "elevenlabs/convai-phone-numbers",
    "payload": {
      "phone_number": "+12025550168",
      "label": "Apicity phone-number route test",
      "provider": "sip_trunk",
      "outbound_trunk_config": {
        "address": "sip.apicity-route-test.invalid",
        "transport": "udp"
      }
    }
  },
  "POST v1.convai.sipTrunk.outboundCall": {
    "source": "elevenlabs/convai-outbound-calls",
    "payload": {
      "agent_id": "apicity-route-test-agent",
      "agent_phone_number_id": "apicity-route-test-phone",
      "to_number": "+15005550006"
    }
  },
  "POST v1.convai.testInvocations.resubmit": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "test_run_ids": [
        "trun_0101kw9vb2keef3bcbyjyk7djx81"
      ],
      "agent_id": "agent_4801kw9vazcbedyt8wgke5n8z0x6"
    }
  },
  "POST v1.convai.tools.create": {
    "source": "elevenlabs/convai-tools",
    "payload": {
      "tool_config": {
        "type": "webhook",
        "name": "apicity_route_test_tool",
        "description": "Apicity tools route test webhook.",
        "api_schema": {
          "url": "https://example.com/apicity/route-test",
          "method": "GET"
        }
      }
    }
  },
  "POST v1.convai.twilio.outboundCall": {
    "source": "elevenlabs/convai-outbound-calls",
    "payload": {
      "agent_id": "apicity-route-test-agent",
      "agent_phone_number_id": "apicity-route-test-phone",
      "to_number": "+15005550006"
    }
  },
  "POST v1.music": {
    "source": "elevenlabs/music-compose",
    "payload": {
      "prompt": "calm lo-fi piano loop",
      "music_length_ms": 10000,
      "force_instrumental": true
    }
  },
  "POST v1.music.detailed": {
    "source": "elevenlabs/music-detailed",
    "payload": {
      "prompt": "calm lo-fi piano loop",
      "music_length_ms": 10000,
      "force_instrumental": true
    }
  },
  "POST v1.music.plan": {
    "source": "elevenlabs/music-plan",
    "payload": {
      "prompt": "calm lo-fi piano loop",
      "music_length_ms": 10000
    }
  },
  "POST v1.music.stream": {
    "source": "elevenlabs/music-stream",
    "payload": {
      "prompt": "calm lo-fi piano loop",
      "music_length_ms": 10000,
      "force_instrumental": true
    }
  },
  "POST v1.productions.orders.create": {
    "source": "elevenlabs/productions-orders",
    "payload": {
      "sandbox": true
    }
  },
  "POST v1.productions.orders.items.upsert": {
    "source": "elevenlabs/productions-orders",
    "payload": {
      "request": {
        "item": {
          "kind": "dub",
          "media_id": "prodmedia_01jgb2zd68f8f9tfvbb968wb8z",
          "source_language": "en",
          "destination_languages": [
            "es",
            "fr"
          ],
          "include_captions": true,
          "include_source_captions": false
        }
      }
    }
  },
  "POST v1.soundGeneration": {
    "source": "elevenlabs/sound-generation",
    "payload": {
      "text": "soft ui click",
      "duration_seconds": 0.5,
      "prompt_influence": 0.3
    }
  },
  "POST v1.speechEngine.create": {
    "source": "elevenlabs/speech-engine",
    "payload": {
      "name": "Apicity Speech Engine route test",
      "speech_engine": {
        "ws_url": "wss://example.com/transcript",
        "request_headers": {
          "authorization": {
            "variable_name": "transcript_auth"
          }
        }
      },
      "language": "en",
      "tags": [
        "apicity"
      ]
    }
  },
  "POST v1.studio.podcasts.create": {
    "source": "elevenlabs/studio",
    "payload": {
      "model_id": "eleven_multilingual_v2",
      "mode": {
        "type": "bulletin",
        "bulletin": {
          "host_voice_id": "apicity-fake-voice"
        }
      },
      "source": {
        "type": "text",
        "text": "Hello from apicity."
      }
    }
  },
  "POST v1.textToSpeech.stream": {
    "source": "elevenlabs/text-to-speech-stream",
    "payload": {
      "text": "Hello from the streaming endpoint.",
      "model_id": "eleven_multilingual_v2"
    }
  },
  "POST v1.textToSpeech.stream.withTimestamps": {
    "source": "elevenlabs/text-to-speech-stream-with-timestamps",
    "payload": {
      "text": "Streaming with timestamps.",
      "model_id": "eleven_multilingual_v2"
    }
  },
  "POST v1.textToSpeech.withTimestamps": {
    "source": "elevenlabs/text-to-speech-with-timestamps",
    "payload": {
      "text": "Timestamps please.",
      "model_id": "eleven_multilingual_v2"
    }
  },
  "POST v1.textToVoice": {
    "source": "elevenlabs/text-to-voice",
    "payload": {
      "voice_name": "Apicity Test Narrator",
      "voice_description": "A warm, friendly middle-aged narrator with a calm British accent.",
      "generated_voice_id": "4leCOcdTmRHiiAQF2IbG"
    }
  },
  "POST v1.textToVoice.design": {
    "source": "elevenlabs/text-to-voice",
    "payload": {
      "voice_description": "A warm, friendly middle-aged narrator with a calm British accent.",
      "auto_generate_text": true
    }
  },
  "POST v1.textToVoice.remix": {
    "source": "elevenlabs/text-to-voice",
    "payload": {
      "voice_description": "Make it brighter and more energetic.",
      "auto_generate_text": true
    }
  },
  "POST v1.voices.pvc": {
    "source": "elevenlabs/pvc-voice-create",
    "payload": {
      "name": "Apicity PVC route test",
      "language": "en",
      "description": null,
      "labels": {
        "language": "en",
        "accent": "en-US"
      }
    }
  },
  "POST v1.voices.pvc.samples": {
    "source": "elevenlabs/voice-pvc-sample-update",
    "payload": {
      "remove_background_noise": false,
      "selected_speaker_ids": null,
      "trim_start_time": null,
      "trim_end_time": null,
      "file_name": "apicity-sample.wav"
    }
  },
  "POST v1.voices.pvc.train": {
    "source": "elevenlabs/pvc-train",
    "payload": {
      "model_id": "eleven_turbo_v2"
    }
  },
  "POST v1.voices.settings.edit": {
    "source": "elevenlabs/voice-crud",
    "payload": {
      "stability": 0.4,
      "similarity_boost": 0.8
    }
  },
  "POST v1.workspace.analytics.query.usageByProductOverTime": {
    "source": "elevenlabs/workspace-usage-by-product-over-time",
    "payload": {
      "start_time": 1767225600000,
      "end_time": 1767312000000,
      "interval_seconds": 86400,
      "group_by": [
        "product_type"
      ],
      "time_zone": "UTC"
    }
  },
  "POST v1.workspace.analytics.requests": {
    "source": "elevenlabs/workspace-analytics-requests",
    "payload": {
      "start_time": 4102444800000,
      "limit": 1,
      "sort": "asc"
    }
  },
  "PUT v1.convai.agentTesting.update": {
    "source": "elevenlabs/convai-agent-testing",
    "payload": {
      "name": "Apicity route response test updated",
      "type": "llm",
      "chat_history": [
        {
          "role": "user",
          "message": "Say hello from Apicity in one short sentence.",
          "time_in_call_secs": 0
        }
      ],
      "success_condition": "The agent responds with a short greeting that mentions Apicity.",
      "parent_folder_id": "tfld_4801kw9vb0v1ewp9h2c1dc7893yv"
    }
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
