// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.convai.agents.list": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "page_size": 30
    }
  },
  "GET v2.voices": {
    "source": "elevenlabs/voices",
    "payload": {
      "page_size": 1,
      "voice_type": "default",
      "include_total_count": true
    }
  },
  "PATCH v1.convai.agents.update": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "name": "Apicity agents route test (updated)"
    }
  },
  "POST v1.convai.agents.create": {
    "source": "elevenlabs/convai-agents",
    "payload": {
      "name": "Apicity agents route test",
      "conversation_config": {
        "agent": {
          "prompt": {
            "prompt": "You are a helpful Apicity route-test assistant."
          },
          "first_message": "Hello from Apicity.",
          "language": "en"
        }
      },
      "tags": [
        "apicity-test"
      ]
    }
  },
  "POST v1.soundGeneration": {
    "source": "elevenlabs/sound-generation",
    "payload": {
      "text": "soft ui click",
      "duration_seconds": 0.5,
      "prompt_influence": 0.3
    }
  },
  "POST v1.voices.pvc": {
    "source": "elevenlabs/pvc-voice-create",
    "payload": {
      "name": "Apicity PVC route test",
      "language": "en",
      "description": null,
      "labels": {
        "language": "en",
        "accent": "en-US"
      }
    }
  },
  "POST v1.voices.pvc.samples": {
    "source": "elevenlabs/voice-pvc-sample-update",
    "payload": {
      "remove_background_noise": false,
      "selected_speaker_ids": null,
      "trim_start_time": null,
      "trim_end_time": null,
      "file_name": "apicity-sample.wav"
    }
  },
  "POST v1.voices.pvc.train": {
    "source": "elevenlabs/pvc-train",
    "payload": {
      "model_id": "eleven_turbo_v2"
    }
  },
  "POST v1.workspace.analytics.query.usageByProductOverTime": {
    "source": "elevenlabs/workspace-usage-by-product-over-time",
    "payload": {
      "start_time": 1767225600000,
      "end_time": 1767312000000,
      "interval_seconds": 86400,
      "group_by": [
        "product_type"
      ],
      "time_zone": "UTC"
    }
  },
  "POST v1.workspace.analytics.requests": {
    "source": "elevenlabs/workspace-analytics-requests",
    "payload": {
      "start_time": 4102444800000,
      "limit": 1,
      "sort": "asc"
    }
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
