export { createElevenLabs } from "./elevenlabs";

export { ElevenLabsError } from "./types";

export type {
  ElevenLabsOptions,
  ElevenLabsSoundGenerationRequest,
  ElevenLabsSoundGenerationMethod,
  ElevenLabsTextToDialogueRequest,
  ElevenLabsTextToDialogueMethod,
  ElevenLabsTextToSpeechRequest,
  ElevenLabsTextToSpeechMethod,
  ElevenLabsSpeechToTextRequest,
  ElevenLabsSpeechToTextResponse,
  ElevenLabsSpeechToTextMethod,
  ElevenLabsTranscript,
  ElevenLabsTranscriptWord,
  ElevenLabsTranscriptWordType,
  ElevenLabsTranscriptCharacter,
  ElevenLabsTranscriptAdditionalFormat,
  ElevenLabsTranscriptEntity,
  ElevenLabsMultichannelTranscript,
  ElevenLabsWebhookAcknowledgement,
  ElevenLabsMoneyAmount,
  ElevenLabsInvoiceDiscount,
  ElevenLabsInvoice,
  ElevenLabsPendingSubscriptionChange,
  ElevenLabsSubscription,
  ElevenLabsUserSubscriptionResponse,
  ElevenLabsUserSubscriptionMethod,
  ElevenLabsUserNamespace,
  ElevenLabsV1Namespace,
  ElevenLabsPostV1Namespace,
  ElevenLabsPostNamespace,
  ElevenLabsGetV1Namespace,
  ElevenLabsGetNamespace,
  ElevenLabsProvider,
} from "./types";
