// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.googleFlow.accounts.captchaStats": {
    "source": "google-flow/contracts",
    "payload": {
      "anonymized": true,
      "date": "2026-06-25",
      "limit": 10
    }
  },
  "GET v1.googleFlow.characters": {
    "source": "google-flow/contracts",
    "payload": {
      "email": "user@example.com"
    }
  },
  "GET v1.googleFlow.jobs": {
    "source": "google-flow/contracts",
    "payload": {
      "options": "history"
    }
  },
  "GET v1.googleFlow.voices": {
    "source": "google-flow/contracts",
    "payload": {
      "email": "user@example.com",
      "source": "user"
    }
  },
  "POST v1.googleFlow.accounts": {
    "source": "google-flow/contracts",
    "payload": {
      "cookies": "SID=fixture;"
    }
  },
  "POST v1.googleFlow.accounts.captchaProviders": {
    "source": "google-flow/contracts",
    "payload": {
      "CapSolver": "provider-key"
    }
  },
  "POST v1.googleFlow.characters": {
    "source": "google-flow/contracts",
    "payload": {
      "displayName": "Ari",
      "imageReference_1": "media-1"
    }
  },
  "POST v1.googleFlow.images": {
    "source": "google-flow/contracts",
    "payload": {
      "prompt": "A clean product photo",
      "count": 1
    }
  },
  "POST v1.googleFlow.images.upscale": {
    "source": "google-flow/contracts",
    "payload": {
      "mediaGenerationId": "image-1",
      "resolution": "2k"
    }
  },
  "POST v1.googleFlow.videos": {
    "source": "google-flow/contracts",
    "payload": {
      "prompt": "A slow camera push through a studio",
      "count": 1
    }
  },
  "POST v1.googleFlow.videos.concatenate": {
    "source": "google-flow/contracts",
    "payload": {
      "media": [
        {
          "mediaGenerationId": "video-1",
          "trimStart": 1
        },
        {
          "mediaGenerationId": "video-2",
          "trimEnd": 1
        }
      ]
    }
  },
  "POST v1.googleFlow.videos.extend": {
    "source": "google-flow/contracts",
    "payload": {
      "mediaGenerationId": "video-1",
      "prompt": "Continue the motion"
    }
  },
  "POST v1.googleFlow.videos.gif": {
    "source": "google-flow/contracts",
    "payload": {
      "mediaGenerationId": "video-1"
    }
  },
  "POST v1.googleFlow.videos.upscale": {
    "source": "google-flow/contracts",
    "payload": {
      "mediaGenerationId": "video-1",
      "resolution": "1080p"
    }
  },
  "POST v1.googleFlow.voices": {
    "source": "google-flow/contracts",
    "payload": {
      "email": "user@example.com",
      "voice": "Aoede",
      "displayName": "Narrator",
      "dialog": "Hello there",
      "voicePerformance": "Warm and clear"
    }
  },
  "POST v1.publishers.google.models.countTokens": {
    "source": "google/count-tokens",
    "payload": {
      "contents": [
        {
          "role": "user",
          "parts": [
            {
              "text": "Count the tokens in this short prompt."
            }
          ]
        }
      ]
    }
  },
  "POST v1.publishers.google.models.generateContent": {
    "source": "google/generate-content",
    "payload": {
      "contents": [
        {
          "role": "user",
          "parts": [
            {
              "text": "Say hello in one short sentence."
            }
          ]
        }
      ],
      "generationConfig": {
        "temperature": 0,
        "thinkingConfig": {
          "thinkingBudget": 0
        },
        "maxOutputTokens": 32
      }
    }
  },
  "POST v1internal.retrieveUserQuota": {
    "source": "google/antigravity-usage",
    "payload": {}
  },
  "POST v1internal.retrieveUserQuotaSummary": {
    "source": "google/antigravity-quota-summary",
    "payload": {}
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
