// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "POST inference.v1.accounts.rlorTrainerJobs.create": {
    "source": "fireworks/rlor-trainer-jobs-create",
    "payload": {
      "dataset": "accounts/jwtanner/datasets/test-rlor-dataset",
      "evaluator": "accounts/jwtanner/evaluators/test-evaluator",
      "displayName": "Test RLOR Trainer Job",
      "trainingConfig": {
        "baseModel": "accounts/fireworks/models/llama-v3p1-8b-instruct",
        "epochs": 1,
        "learningRate": 0.00001
      }
    }
  },
  "POST inference.v1.accounts.rlorTrainerJobs.executeTrainStep": {
    "source": "fireworks/rlor-trainer-jobs-execute-step",
    "payload": {
      "dataset": "accounts/jwtanner/datasets/step-dataset",
      "outputModel": "accounts/jwtanner/models/step-output-model"
    }
  },
  "POST inference.v1.chat.completions": {
    "source": "fireworks/chat-hello",
    "payload": {
      "model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
      "messages": [
        {
          "role": "user",
          "content": "Say hello in one sentence."
        }
      ],
      "temperature": 0,
      "max_tokens": 64
    }
  },
  "POST inference.v1.completions": {
    "source": "fireworks/completions-hello",
    "payload": {
      "model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
      "prompt": "The capital of France is",
      "max_tokens": 32,
      "temperature": 0
    }
  },
  "POST inference.v1.embeddings": {
    "source": "fireworks/embeddings-hello",
    "payload": {
      "model": "nomic-ai/nomic-embed-text-v1.5",
      "input": "Hello world"
    }
  },
  "POST inference.v1.messages": {
    "source": "fireworks/messages-hello",
    "payload": {
      "model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
      "messages": [
        {
          "role": "user",
          "content": "Say hello in one sentence."
        }
      ],
      "max_tokens": 64
    }
  },
  "POST inference.v1.rerank": {
    "source": "fireworks/rerank-basic",
    "payload": {
      "model": "fireworks/qwen3-reranker-8b",
      "query": "What is the capital of France?",
      "documents": [
        "Berlin is the capital of Germany.",
        "Paris is the capital and largest city of France.",
        "Madrid is the capital of Spain."
      ],
      "top_n": 2,
      "return_documents": true
    }
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
