// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har, plus static
// examples for providers that intentionally avoid live-network recordings.
//
// Each entry is a green-path payload for one endpoint. `attachExamples`
// walks the provider tree and hangs the matching entry off each endpoint
// function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET getavailablegroups": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getavailableleagues": {
    "source": "static:openligadb-public-catalog",
    "payload": {},
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getavailableleagues.bySeason": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "season": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getavailablesports": {
    "source": "static:openligadb-public-catalog",
    "payload": {},
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getavailableteams": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getbltable": {
    "source": "static:openligadb-standings",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getcurrentgroup": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "leagueShortcut": "bl1"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getgoalgetters": {
    "source": "static:openligadb-scorers",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getgrouptable": {
    "source": "static:openligadb-standings",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getlastchangedate": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024,
      "groupOrderId": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getmatchdata.byId": {
    "source": "static:openligadb-matchdata",
    "payload": {
      "matchId": 68720
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getmatchdata.byLeagueSeason": {
    "source": "static:openligadb-matchdata",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getmatchdata.byLeagueSeasonGroup": {
    "source": "static:openligadb-matchdata",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024,
      "groupOrderId": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getmatchdata.byLeagueSeasonTeam": {
    "source": "static:openligadb-matchdata",
    "payload": {
      "leagueShortcut": "bl1",
      "leagueSeason": 2024,
      "teamFilterstring": "Bayern"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getmatchdata.byTeams": {
    "source": "static:openligadb-matchdata",
    "payload": {
      "teamId1": 16,
      "teamId2": 40
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET getresultinfos": {
    "source": "static:openligadb-public-catalog",
    "payload": {
      "leagueId": 4500
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET swagger.v1.swaggerJson": {
    "source": "static:openligadb-openapi-document",
    "payload": {},
    "tier": "cheap",
    "runByDefault": true
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
