export { createOpenLigaDB } from "./openligadb";
export {
  buildOpenLigaDBPath,
  buildOpenLigaDBQuery,
  createOpenLigaDBRequest,
  encodeOpenLigaDBPathSegment,
} from "./openligadb";
export { OpenLigaDBError } from "./types";

export type {
  OpenLigaDBAvailableGroupsMethod,
  OpenLigaDBAvailableGroupsResponse,
  OpenLigaDBAvailableLeaguesMethod,
  OpenLigaDBAvailableLeaguesResponse,
  OpenLigaDBAvailableSportsMethod,
  OpenLigaDBAvailableSportsResponse,
  OpenLigaDBAvailableTeamsMethod,
  OpenLigaDBAvailableTeamsResponse,
  OpenLigaDBBlTableMethod,
  OpenLigaDBBlTableResponse,
  OpenLigaDBBlTableTeam,
  OpenLigaDBCurrentGroupMethod,
  OpenLigaDBCurrentGroupRequest,
  OpenLigaDBCurrentGroupResponse,
  OpenLigaDBGetNamespace,
  OpenLigaDBGetMatchdataNamespace,
  OpenLigaDBGlobalResultInfo,
  OpenLigaDBGoal,
  OpenLigaDBGoalGettersMethod,
  OpenLigaDBGoalGettersResponse,
  OpenLigaDBGoalGetter,
  OpenLigaDBGroup,
  OpenLigaDBJsonObject,
  OpenLigaDBLastChangeDateMethod,
  OpenLigaDBLastChangeDateRequest,
  OpenLigaDBLastChangeDateResponse,
  OpenLigaDBLeague,
  OpenLigaDBLeagueSeasonRequest,
  OpenLigaDBLocation,
  OpenLigaDBMatch,
  OpenLigaDBMatchByIdMethod,
  OpenLigaDBMatchByIdRequest,
  OpenLigaDBMatchByIdResponse,
  OpenLigaDBMatchesByLeagueSeasonGroupMethod,
  OpenLigaDBMatchesByLeagueSeasonGroupRequest,
  OpenLigaDBMatchesByLeagueSeasonGroupResponse,
  OpenLigaDBMatchesByLeagueSeasonMethod,
  OpenLigaDBMatchesByLeagueSeasonRequest,
  OpenLigaDBMatchesByLeagueSeasonResponse,
  OpenLigaDBMatchesByLeagueSeasonTeamMethod,
  OpenLigaDBMatchesByLeagueSeasonTeamRequest,
  OpenLigaDBMatchesByLeagueSeasonTeamResponse,
  OpenLigaDBMatchesByTeamsMethod,
  OpenLigaDBMatchesByTeamsRequest,
  OpenLigaDBMatchesByTeamsResponse,
  OpenLigaDBMatchResult,
  OpenLigaDBMethod,
  OpenLigaDBNoRequestMethod,
  OpenLigaDBOptions,
  OpenLigaDBPathSegment,
  OpenLigaDBProvider,
  OpenLigaDBQueryValue,
  OpenLigaDBRequestFunction,
  OpenLigaDBRequestMethod,
  OpenLigaDBRequestOptions,
  OpenLigaDBResultInfo,
  OpenLigaDBResultInfosMethod,
  OpenLigaDBResultInfosRequest,
  OpenLigaDBResultInfosResponse,
  OpenLigaDBSeasonRequest,
  OpenLigaDBSport,
  OpenLigaDBSwaggerDocument,
  OpenLigaDBSwaggerJsonMethod,
  OpenLigaDBSwaggerNamespace,
  OpenLigaDBSwaggerV1Namespace,
  OpenLigaDBTeam,
} from "./types";

export {
  OpenLigaDBBlTableResponseSchema,
  OpenLigaDBBlTableTeamSchema,
  OpenLigaDBCurrentGroupRequestSchema,
  OpenLigaDBGoalGettersResponseSchema,
  OpenLigaDBGoalGetterSchema,
  OpenLigaDBGoalSchema,
  OpenLigaDBGlobalResultInfoSchema,
  OpenLigaDBGroupSchema,
  OpenLigaDBLastChangeDateRequestSchema,
  OpenLigaDBLeagueSchema,
  OpenLigaDBLeagueSeasonRequestSchema,
  OpenLigaDBLocationSchema,
  OpenLigaDBMatchByIdRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonGroupRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonTeamRequestSchema,
  OpenLigaDBMatchesByTeamsRequestSchema,
  OpenLigaDBMatchResultSchema,
  OpenLigaDBMatchSchema,
  OpenLigaDBOptionsSchema,
  OpenLigaDBResultInfoSchema,
  OpenLigaDBResultInfosRequestSchema,
  OpenLigaDBSeasonRequestSchema,
  OpenLigaDBSportSchema,
  OpenLigaDBSwaggerDocumentSchema,
  OpenLigaDBTeamSchema,
} from "./zod";
