export { createOpenLigaDB } from "./openligadb";
export { OpenLigaDBError } from "./types";

export type {
  OpenLigaDBBlTableTeam,
  OpenLigaDBGetMatchdataNamespace,
  OpenLigaDBGlobalResultInfo,
  OpenLigaDBGoal,
  OpenLigaDBGoalGetter,
  OpenLigaDBGroup,
  OpenLigaDBLeague,
  OpenLigaDBLocation,
  OpenLigaDBMatch,
  OpenLigaDBMatchByIdMethod,
  OpenLigaDBMatchByIdRequest,
  OpenLigaDBMatchByIdResponse,
  OpenLigaDBMatchesByLeagueSeasonGroupMethod,
  OpenLigaDBMatchesByLeagueSeasonGroupRequest,
  OpenLigaDBMatchesByLeagueSeasonGroupResponse,
  OpenLigaDBMatchesByLeagueSeasonMethod,
  OpenLigaDBMatchesByLeagueSeasonRequest,
  OpenLigaDBMatchesByLeagueSeasonResponse,
  OpenLigaDBMatchesByLeagueSeasonTeamMethod,
  OpenLigaDBMatchesByLeagueSeasonTeamRequest,
  OpenLigaDBMatchesByLeagueSeasonTeamResponse,
  OpenLigaDBMatchesByTeamsMethod,
  OpenLigaDBMatchesByTeamsRequest,
  OpenLigaDBMatchesByTeamsResponse,
  OpenLigaDBMatchResult,
  OpenLigaDBMethod,
  OpenLigaDBOptions,
  OpenLigaDBProvider,
  OpenLigaDBResultInfo,
  OpenLigaDBSport,
  OpenLigaDBTeam,
} from "./types";

export {
  OpenLigaDBBlTableTeamSchema,
  OpenLigaDBGoalGetterSchema,
  OpenLigaDBGoalSchema,
  OpenLigaDBGlobalResultInfoSchema,
  OpenLigaDBGroupSchema,
  OpenLigaDBLeagueSchema,
  OpenLigaDBLocationSchema,
  OpenLigaDBMatchByIdRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonGroupRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonRequestSchema,
  OpenLigaDBMatchesByLeagueSeasonTeamRequestSchema,
  OpenLigaDBMatchesByTeamsRequestSchema,
  OpenLigaDBMatchResultSchema,
  OpenLigaDBMatchSchema,
  OpenLigaDBOptionsSchema,
  OpenLigaDBResultInfoSchema,
  OpenLigaDBSportSchema,
  OpenLigaDBTeamSchema,
} from "./zod";
