// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET api.v1.aleph.recordInfo": {
    "source": "kie/aleph/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.flux.kontext.recordInfo": {
    "source": "kie/flux-kontext-record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.generate.recordInfo": {
    "source": "kie/suno/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.gpt4oImage.recordInfo": {
    "source": "kie/gpt4o-image/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.jobs.recordInfo": {
    "source": "kie/bytedance-seedance-2",
    "payload": {
      "taskId": "49265b81be9607661c0246b892144776"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.lyrics.recordInfo": {
    "source": "kie/suno/lyrics-record-info",
    "payload": {
      "taskId": "apicity-test-nonexistent-lyrics-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.midi.recordInfo": {
    "source": "kie/midi/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.mj.recordInfo": {
    "source": "kie/mj/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-mj-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.mp4.recordInfo": {
    "source": "kie/mp4/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.runway.recordDetail": {
    "source": "kie/runway/record-detail-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.suno.cover.recordInfo": {
    "source": "kie/suno/cover-record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.veo.get1080pVideo": {
    "source": "kie/veo/get-1080p-video",
    "payload": {
      "taskId": "apicity-test-veo-1080p-not-found",
      "index": 0
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.veo.recordInfo": {
    "source": "kie/veo/aspect-ratio-probe",
    "payload": {
      "taskId": "833080d158b26214aeb43071aadac0d0"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.vocalRemoval.recordInfo": {
    "source": "kie/suno/vocal-removal-record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.voice.recordInfo": {
    "source": "kie/suno/voice-record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.voice.validateInfo": {
    "source": "kie/suno/voice-validate-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET api.v1.wav.recordInfo": {
    "source": "kie/wav/record-info-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.fileBase64Upload": {
    "source": "kie/file-uploads/base64",
    "payload": {
      "base64Data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFCcSAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
      "uploadPath": "images/test-uploads",
      "fileName": "test-base64.png",
      "mimeType": "image/png"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.common.downloadUrl": {
    "source": "kie/download-url/convert",
    "payload": {
      "url": "https://cdn.kie.ai/files/sample-test-file.mp4"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.flux.kontext.generate": {
    "source": "kie/flux-kontext-generate",
    "payload": {
      "prompt": "A cinematic night city poster with neon reflections on a rainy street.",
      "aspectRatio": "16:9",
      "model": "flux-kontext-pro",
      "outputFormat": "jpeg"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate": {
    "source": "kie/suno/generate-submit",
    "payload": {
      "prompt": "A short upbeat lo-fi loop, gentle piano, no vocals, summer afternoon",
      "model": "V4_5",
      "instrumental": true,
      "customMode": false,
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.addInstrumental": {
    "source": "kie/suno/add-instrumental-submit",
    "payload": {
      "uploadUrl": "https://example.com/vocal.mp3",
      "title": "Gentle Acoustic Backing",
      "tags": "gentle acoustic guitar, piano",
      "negativeTags": "distortion, harsh noise",
      "callBackUrl": "https://example.com/cb",
      "model": "V4_5PLUS"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.addVocals": {
    "source": "kie/suno/add-vocals-submit",
    "payload": {
      "uploadUrl": "https://example.com/instrumental.mp3",
      "prompt": "Add soft female vocals about summer dreams",
      "title": "Summer Dreams",
      "style": "soft pop",
      "negativeTags": "heavy metal, strong drum beats",
      "callBackUrl": "https://example.com/cb",
      "model": "V4_5PLUS"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.extend": {
    "source": "kie/suno/extend-bogus-audio-id",
    "payload": {
      "defaultParamFlag": true,
      "audioId": "apicity-test-bogus-audio-id",
      "prompt": "extend with a bridge",
      "model": "V5",
      "callBackUrl": "https://example.com/cb",
      "style": "Synthwave",
      "title": "Side B",
      "continueAt": 30
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.getTimestampedLyrics": {
    "source": "kie/suno/get-timestamped-lyrics-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real",
      "audioId": "apicity-test-nonexistent-audio-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.mashup": {
    "source": "kie/suno/mashup-submit",
    "payload": {
      "uploadUrlList": [
        "https://example.com/audio1.mp3",
        "https://example.com/audio2.mp3"
      ],
      "customMode": false,
      "model": "V4",
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.replaceSection": {
    "source": "kie/suno/replace-music-section-full-lyrics-validation",
    "payload": {
      "taskId": "test-task-id",
      "audioId": "test-audio-id",
      "prompt": "Replace with upbeat electronic section",
      "tags": "electronic, upbeat",
      "title": "Test Replacement",
      "infillStartS": 10,
      "infillEndS": 20,
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.sounds": {
    "source": "kie/suno/sounds-generate-submit",
    "payload": {
      "prompt": "Rain falling on a tin roof, gentle thunder in distance",
      "model": "V5",
      "soundLoop": true,
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.uploadCover": {
    "source": "kie/suno/upload-cover-bogus-url",
    "payload": {
      "uploadUrl": "https://invalid-host-apicity-test.invalid/song.mp3",
      "prompt": "Cover this in a synthwave style",
      "customMode": true,
      "instrumental": false,
      "model": "V5",
      "callBackUrl": "https://example.com/cb",
      "style": "Synthwave",
      "title": "Cover Take"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.generate.uploadExtend": {
    "source": "kie/suno/upload-extend-bogus-url",
    "payload": {
      "uploadUrl": "https://invalid-host-apicity-test.invalid/song.mp3",
      "defaultParamFlag": true,
      "instrumental": false,
      "continueAt": 60,
      "model": "V5",
      "callBackUrl": "https://example.com/cb",
      "prompt": "Continue the chorus then resolve"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.gpt4oImage.downloadUrl": {
    "source": "kie/gpt4o-image/download-url-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real",
      "url": "https://tempfile.aiquickdraw.com/v/apicity-test-nonexistent.png"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.gpt4oImage.generate": {
    "source": "kie/gpt4o-image-generate",
    "payload": {
      "prompt": "A cinematic night city poster with neon reflections on a rainy street.",
      "size": "3:2",
      "isEnhance": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.jobs.createTask": {
    "source": "kie/grok-video-upscale",
    "payload": {
      "model": "grok-imagine/upscale",
      "input": {
        "task_id": "d43f0d0ab29f28fdfcf68a9dccbd7a42"
      }
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.lyrics": {
    "source": "kie/suno/lyrics-submit",
    "payload": {
      "prompt": "A short song about morning coffee",
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.midi.generate": {
    "source": "kie/suno/midi-bogus-task-id",
    "payload": {
      "taskId": "apicity-test-bogus-vocal-removal-task-id",
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.mj.generate": {
    "source": "kie/mj-generate",
    "payload": {
      "taskType": "mj_txt2img",
      "prompt": "A sci-fi themed fighter jet in a beautiful sky, computer wallpaper",
      "speed": "relaxed",
      "aspectRatio": "16:9",
      "version": "7",
      "stylization": 100,
      "weirdness": 0
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.mp4.generate": {
    "source": "kie/suno/mp4-bogus-ids",
    "payload": {
      "taskId": "apicity-test-bogus-task-id",
      "audioId": "apicity-test-bogus-audio-id",
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.omni.audio.create": {
    "source": "kie/audio/gemini-omni-audio-create",
    "payload": {
      "audio_id": "achernar",
      "name": "Apicity HAR Test Narrator",
      "voice_description": "A calm, clear, friendly voice for a short API smoke test.",
      "example_dialogue": "Hello from the Apicity Kie audio HAR test."
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.runway.extend": {
    "source": "kie/runway/extend-not-found",
    "payload": {
      "taskId": "apicity-test-nonexistent-task-id-do-not-record-real",
      "prompt": "Continue the scene with a slow zoom out.",
      "quality": "720p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.runway.generate": {
    "source": "kie/runway-generate",
    "payload": {
      "prompt": "A serene drone shot flying over a misty pine forest at dawn.",
      "duration": 5,
      "quality": "720p",
      "aspectRatio": "16:9",
      "callBackUrl": "https://example.com/runway-callback"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.style.generate": {
    "source": "kie/suno/style-boost",
    "payload": {
      "content": "Pop, Mysterious"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.veo.generate": {
    "source": "kie/veo/aspect-ratio-probe",
    "payload": {
      "prompt": "Apicity aspect probe camelCase: solid blue sky, still camera, no people",
      "model": "veo3_lite",
      "generationType": "TEXT_2_VIDEO",
      "aspectRatio": "9:16",
      "duration": 4,
      "resolution": "720p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.vocalRemoval.generate": {
    "source": "kie/suno/vocal-removal-bogus-ids",
    "payload": {
      "taskId": "apicity-test-bogus-task-id",
      "audioId": "apicity-test-bogus-audio-id",
      "callBackUrl": "https://example.com/cb",
      "type": "separate_vocal"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.voice.checkVoice": {
    "source": "kie/suno/voice-check-voice-not-found",
    "payload": {
      "task_id": "apicity-test-nonexistent-task-id-do-not-record-real"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST api.v1.wav.generate": {
    "source": "kie/suno/wav-bogus-ids",
    "payload": {
      "taskId": "apicity-test-bogus-task-id",
      "audioId": "apicity-test-bogus-audio-id",
      "callBackUrl": "https://example.com/cb"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST claude.v1.messages": {
    "source": "kie/claude-chat-hello",
    "payload": {
      "model": "claude-sonnet-4-6",
      "messages": [
        {
          "role": "user",
          "content": "Say hello in one sentence."
        }
      ],
      "stream": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gemini25Flash.v1.chat.completions": {
    "source": "kie/gemini-25-flash-chat-auth-error",
    "payload": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "ping"
            }
          ]
        }
      ],
      "stream": false,
      "include_thoughts": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gemini25Pro.v1.chat.completions": {
    "source": "kie/gemini-25-pro-chat-auth-error",
    "payload": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "ping"
            }
          ]
        }
      ],
      "stream": false,
      "include_thoughts": false,
      "reasoning_effort": "low"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gemini3Flash.v1.chat.completions": {
    "source": "kie/gemini-3-flash-chat-auth-error",
    "payload": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "ping"
            }
          ]
        }
      ],
      "stream": false,
      "include_thoughts": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gemini3Pro.v1.chat.completions": {
    "source": "kie/gemini-3-pro-chat-auth-error",
    "payload": {
      "messages": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "ping"
            }
          ]
        }
      ],
      "stream": false,
      "include_thoughts": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
