// Export main provider function and helpers
export { createKie, submitMediaJob, uploadFile } from "./kie";

// Export reusable schema metadata
export {
  GeminiOmniAudioCreateRequestSchema,
  GeminiOmniAudioVoiceIdSchema,
  GeminiOmniAudioVoiceIds,
  RecordInfoRequestSchema,
  Seedance2MiniAspectRatioSchema,
  Seedance2MiniInputSchema,
  Seedance2MiniRecordInfoDataSchema,
  Seedance2MiniRecordInfoResponseSchema,
  Seedance2MiniRequestSchema,
  Seedance2MiniResolutionSchema,
  Seedance2MiniTaskResultJsonSchema,
  Seedance2MiniTaskStateSchema,
  GeminiOmniVideoAspectRatioSchema,
  GeminiOmniVideoDurationSchema,
  GeminiOmniVideoRequestSchema,
  GeminiOmniVideoResolutionSchema,
  TaskResponseSchema,
  Wan27VideoEditDurationSchema,
  Wan27VideoEditDurationValues,
} from "./zod";

// Export error class
export { KieError } from "./types";

// Export middleware
export {
  withRetry,
  withFallback,
  withRateLimit,
  createRateLimiter,
} from "./middleware";
export type {
  RetryOptions,
  FallbackOptions,
  RateLimiterOptions,
  RateLimiter,
  RateLimitOptions,
} from "./middleware";

// Export sub-provider factory functions
export { createVeoProvider } from "./veo";
export { createSunoProvider } from "./suno";
export { createChatProvider } from "./chat";
export { createClaudeProvider } from "./claude";

// Export SSE utility
export { sseToIterable } from "./sse";

// Export all types
export type {
  KieMediaModel,
  MediaType,
  KlingElement,
  MultiShotPrompt,
  KlingVideoRequest,
  KlingVideoRequestInput,
  KlingVideoParsedRequest,
  KlingMotionControlRequest,
  KlingMotionControlRequestInput,
  KlingMotionControlParsedRequest,
  KlingV3TurboImageToVideoRequest,
  KlingV3TurboImageToVideoRequestInput,
  KlingV3TurboImageToVideoParsedRequest,
  KlingV3TurboTextToVideoRequest,
  KlingV3TurboTextToVideoRequestInput,
  KlingV3TurboTextToVideoParsedRequest,
  GrokTextToImageRequest,
  GrokTextToImageRequestInput,
  GrokTextToImageParsedRequest,
  GrokImageToImageRequest,
  GrokImageToImageRequestInput,
  GrokImageToImageParsedRequest,
  GrokTextToVideoRequest,
  GrokTextToVideoRequestInput,
  GrokTextToVideoParsedRequest,
  GrokImageToVideoRequest,
  GrokImageToVideoRequestInput,
  GrokImageToVideoParsedRequest,
  GrokVideo15PreviewRequest,
  GrokVideo15PreviewRequestInput,
  GrokVideo15PreviewParsedRequest,
  GrokVideoExtendRequest,
  GrokVideoExtendRequestInput,
  GrokVideoExtendParsedRequest,
  GrokVideoUpscaleRequest,
  GrokVideoUpscaleRequestInput,
  GrokVideoUpscaleParsedRequest,
  NanoBananaProRequest,
  NanoBananaProRequestInput,
  NanoBananaProParsedRequest,
  NanoBanana2Request,
  NanoBanana2RequestInput,
  NanoBanana2ParsedRequest,
  GptImageToImageRequest,
  GptImageToImageRequestInput,
  GptImageToImageParsedRequest,
  GptImage2ImageToImageRequest,
  GptImage2ImageToImageRequestInput,
  GptImage2ImageToImageParsedRequest,
  GptImage2TextToImageRequest,
  GptImage2TextToImageRequestInput,
  GptImage2TextToImageParsedRequest,
  SeedreamImageToImageRequest,
  SeedreamImageToImageRequestInput,
  SeedreamImageToImageParsedRequest,
  SeedreamTextToImageRequest,
  SeedreamTextToImageRequestInput,
  SeedreamTextToImageParsedRequest,
  Qwen2TextToImageRequest,
  Qwen2TextToImageRequestInput,
  Qwen2TextToImageParsedRequest,
  Qwen2ImageEditRequest,
  Qwen2ImageEditRequestInput,
  Qwen2ImageEditParsedRequest,
  Seedance2FastRequest,
  Seedance2FastRequestInput,
  Seedance2FastParsedRequest,
  Seedance2Request,
  Seedance2RequestInput,
  Seedance2ParsedRequest,
  Seedance2MiniInput,
  Seedance2MiniRequest,
  Seedance2MiniRequestInput,
  Seedance2MiniParsedRequest,
  Seedance2MiniTaskResultJson,
  Seedance2MiniRecordInfoData,
  Seedance2MiniRecordInfoResponse,
  Wan27ImageToVideoRequest,
  Wan27ImageToVideoRequestInput,
  Wan27ImageToVideoParsedRequest,
  Wan27TextToVideoRequest,
  Wan27TextToVideoRequestInput,
  Wan27TextToVideoParsedRequest,
  Wan27RefToVideoRequest,
  Wan27RefToVideoRequestInput,
  Wan27RefToVideoParsedRequest,
  Wan27VideoEditRequest,
  Wan27VideoEditRequestInput,
  Wan27VideoEditParsedRequest,
  Wan27ImageColorPalette,
  Wan27ImageRequest,
  Wan27ImageRequestInput,
  Wan27ImageParsedRequest,
  Wan27ImageProRequest,
  Wan27ImageProRequestInput,
  Wan27ImageProParsedRequest,
  SoraWatermarkRequest,
  SoraWatermarkRequestInput,
  SoraWatermarkParsedRequest,
  MediaGenerationRequest,
  MediaGenerationRequestInput,
  MediaGenerationParsedRequest,
  RecordInfoRequest,
  RecordInfoRequestInput,
  KieOptions,
  KieApproval,
  KieProvider,
  KieApiEnvelope,
  TaskResponse,
  TaskResponseParsed,
  KieTaskState,
  KieTaskInfoData,
  KieTaskInfo,
  KieCreditsResponse,
  DownloadUrlRequest,
  DownloadUrlRequestInput,
  DownloadUrlParsedRequest,
  DownloadUrlResponse,
  UploadMediaRequest,
  UploadMediaRequestInput,
  UploadMediaParsedRequest,
  UploadMediaResponse,
  UploadFileData,
  FileUrlUploadRequest,
  FileUrlUploadRequestInput,
  FileUrlUploadParsedRequest,
  FileBase64UploadRequest,
  FileBase64UploadRequestInput,
  FileBase64UploadParsedRequest,
  PayloadFieldSchema,
  ModelInputSchema,
  // Standalone parameter union types
  KlingDuration,
  KlingAspectRatio,
  KlingMode,
  KlingV3TurboDuration,
  KlingV3TurboResolution,
  KlingV3TurboAspectRatio,
  GrokImagineMode,
  GrokTextToVideoMode,
  GrokImageToVideoMode,
  GrokTextToVideoAspectRatio,
  GrokImageToVideoAspectRatio,
  GrokTextToVideoDuration,
  GrokImagineDuration,
  GrokImageToVideoDuration,
  GrokImagineResolution,
  GrokVideo15AspectRatio,
  NanoBananaResolution,
  NanoBananaOutputFormat,
  GptImageQuality,
  GptImage2ImageToImageAspectRatio,
  GptImage2ImageToImageResolution,
  GptImage2TextToImageAspectRatio,
  GptImage2TextToImageResolution,
  Wan27Resolution,
  Wan27AspectRatio,
  Wan27AudioSetting,
  Wan27ImageResolution,
  Wan27ImageAspectRatio,
  Wan27VideoEditDuration,
  Seedance2MiniResolution,
  Seedance2MiniAspectRatio,
  Seedance2MiniTaskState,
  HappyHorseResolution,
  HappyHorseAspectRatio,
  HappyHorse11AspectRatio,
  HappyHorseAudioSetting,
  HappyHorseDuration,
  Omnihuman15OutputResolution,
  VolcengineVideoToVideoLipSyncMode,
  GeminiOmniVideoDuration,
  GeminiOmniVideoAspectRatio,
  GeminiOmniVideoResolution,
  HappyHorseTextToVideoRequest,
  HappyHorseTextToVideoRequestInput,
  HappyHorseTextToVideoParsedRequest,
  HappyHorseImageToVideoRequest,
  HappyHorseImageToVideoRequestInput,
  HappyHorseImageToVideoParsedRequest,
  HappyHorseReferenceToVideoRequest,
  HappyHorseReferenceToVideoRequestInput,
  HappyHorseReferenceToVideoParsedRequest,
  HappyHorseVideoEditRequest,
  HappyHorseVideoEditRequestInput,
  HappyHorseVideoEditParsedRequest,
  HappyHorse11TextToVideoRequest,
  HappyHorse11TextToVideoRequestInput,
  HappyHorse11TextToVideoParsedRequest,
  HappyHorse11ImageToVideoRequest,
  HappyHorse11ImageToVideoRequestInput,
  HappyHorse11ImageToVideoParsedRequest,
  HappyHorse11ReferenceToVideoRequest,
  HappyHorse11ReferenceToVideoRequestInput,
  HappyHorse11ReferenceToVideoParsedRequest,
  HappyHorse11CreateTaskResponse,
  Omnihuman15Request,
  Omnihuman15RequestInput,
  Omnihuman15ParsedRequest,
  VolcengineVideoToVideoLipSyncRequest,
  VolcengineVideoToVideoLipSyncRequestInput,
  VolcengineVideoToVideoLipSyncParsedRequest,
  GeminiOmniVideoRequest,
  GeminiOmniVideoRequestInput,
  GeminiOmniVideoParsedRequest,
  ElevenLabsAudioIsolationRequest,
  ElevenLabsAudioIsolationRequestInput,
  ElevenLabsAudioIsolationParsedRequest,
  ElevenLabsTextToDialogueV3Request,
  ElevenLabsTextToDialogueV3RequestInput,
  ElevenLabsTextToDialogueV3ParsedRequest,
  ElevenLabsTextToSpeechMultilingualV2Request,
  ElevenLabsTextToSpeechMultilingualV2RequestInput,
  ElevenLabsTextToSpeechMultilingualV2ParsedRequest,
  ElevenLabsTextToSpeechTurbo25Request,
  ElevenLabsTextToSpeechTurbo25RequestInput,
  ElevenLabsTextToSpeechTurbo25ParsedRequest,
  ElevenLabsSoundEffectV2Request,
  ElevenLabsSoundEffectV2RequestInput,
  ElevenLabsSoundEffectV2ParsedRequest,
  GeminiOmniAudioVoiceId,
  GeminiOmniAudioCreateRequest,
  GeminiOmniAudioCreateRequestInput,
  GeminiOmniAudioCreateParsedRequest,
  GeminiOmniAudioCreateData,
  GeminiOmniAudioCreateResponse,
} from "./types";

export {
  HappyHorseDurationSchema,
  HappyHorse11AspectRatioSchema,
  HappyHorse11TextToVideoRequestSchema,
  HappyHorse11ImageToVideoRequestSchema,
  HappyHorse11ReferenceToVideoRequestSchema,
  HappyHorse11CreateTaskResponseSchema,
} from "./zod";

// Export sub-provider types
export type {
  VeoModel,
  VeoGenerationType,
  VeoGenerateRequest,
  VeoExtendRequest,
  VeoProvider,
} from "./veo";

export type {
  SunoModel,
  SunoGenerateRequest,
  SunoExtendRequest,
  SunoWavRequest,
  SunoVocalRemovalRequest,
  SunoMp4Request,
  SunoLyricsRequest,
  SunoBoostStyleRequest,
  SunoUploadCoverRequest,
  SunoUploadExtendRequest,
  SunoMidiRequest,
  SunoMashupModel,
  SunoMashupRequest,
  SunoReplaceSectionRequest,
  SunoSoundsModel,
  SunoSoundsKey,
  SunoSoundsRequest,
  SunoAddInstrumentalRequest,
  SunoAddVocalsRequest,
  SunoProvider,
} from "./suno";

export type {
  KieChatContentPart,
  KieChatMessage,
  KieChatRequest,
  KieChatChoice,
  KieChatUsage,
  KieChatResponse,
  KieChatProvider,
} from "./chat";

export type {
  KieClaudeToolInputSchema,
  KieClaudeTool,
  KieClaudeContentPart,
  KieClaudeMessage,
  KieClaudeRequest,
  KieClaudeUsage,
  KieClaudeToolUseContent,
  KieClaudeTextContent,
  KieClaudeContentBlock,
  KieClaudeResponse,
  KieClaudeProvider,
} from "./claude";
export type {
  VeoGenerateRequestInput,
  VeoExtendRequestInput,
  SunoGenerateRequestInput,
  KieChatRequestInput,
  KieClaudeRequestInput,
} from "./zod";
