// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET channels.list": {
    "source": "youtube/channels-list",
    "payload": {
      "part": "snippet",
      "mine": true
    }
  },
  "GET transcripts": {
    "source": "youtube/transcript-id",
    "payload": {
      "v": "dQw4w9WgXcQ"
    }
  },
  "GET videos.list": {
    "source": "youtube/videos-list",
    "payload": {
      "part": "snippet",
      "id": "dQw4w9WgXcQ"
    }
  },
  "POST videos.insert": {
    "source": "youtube/videos-insert",
    "payload": {
      "video": {
        "_file": true,
        "filename": "jump.mp4",
        "contentType": "video/mp4",
        "size": 1318021
      },
      "snippet": {
        "title": "Apicity jump.mp4 test upload",
        "description": "Integration test video uploaded via @apicity/youtube",
        "tags": [
          "apicity",
          "test",
          "integration"
        ],
        "categoryId": "22",
        "defaultLanguage": "en"
      },
      "status": {
        "privacyStatus": "unlisted",
        "embeddable": true,
        "license": "youtube",
        "publicStatsViewable": true,
        "selfDeclaredMadeForKids": false,
        "containsSyntheticMedia": false
      },
      "recordingDetails": {
        "recordingDate": "2026-05-14"
      },
      "localizations": {
        "es": {
          "title": "Prueba de subida jump.mp4",
          "description": "Video de prueba de integracion"
        }
      }
    }
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
