// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har

export interface EndpointExample {
  source: string;
  payload: unknown;
  tier: "cheap" | "expensive" | "prohibitive";
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {};

export default EXAMPLES;

export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const separator = key.indexOf(" ");
    if (separator < 0) continue;
    const segments = key.slice(separator + 1).split(".");
    let current: unknown = root;
    for (const segment of segments) {
      if (
        current === null ||
        (typeof current !== "object" && typeof current !== "function")
      ) {
        current = undefined;
        break;
      }
      current = (current as Record<string, unknown>)[segment];
    }
    if (typeof current === "function") Object.assign(current, { example });
  }
  return provider;
}
