// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.models": {
    "source": "fal/models-search",
    "payload": {
      "limit": 5
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET v1.models.analytics": {
    "source": "fal/analytics",
    "payload": {
      "endpoint_id": "fal-ai/flux/dev"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET v1.models.pricing": {
    "source": "fal/models-pricing",
    "payload": {
      "endpoint_id": "fal-ai/flux/dev"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET v1.models.requests.byEndpoint": {
    "source": "fal/requests",
    "payload": {
      "endpoint_id": "fal-ai/flux/dev",
      "limit": 5
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET v1.models.usage": {
    "source": "fal/models-usage-stats",
    "payload": {
      "endpoint_id": "fal-ai/flux/dev",
      "limit": 5
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "GET v1.workflows": {
    "source": "fal/workflows-list",
    "payload": {
      "limit": 3
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.qwenImage3.edit": {
    "source": "fal/alibaba-qwen-image-3-edit",
    "payload": {
      "prompt": "Give the cat in image 1 a small red knitted scarf.",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "image_size": "square",
      "num_images": 1,
      "output_format": "png"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.qwenImage3.textToImage": {
    "source": "fal/alibaba-qwen-image-3-text-to-image",
    "payload": {
      "prompt": "A serene mountain landscape at sunrise."
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0.imageToVideo": {
    "source": "fal/wan3p0-image-to-video",
    "payload": {
      "prompt": "The cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0.referenceToVideo": {
    "source": "fal/wan3p0-reference-to-video",
    "payload": {
      "prompt": "The cat in Image 1 blinks slowly and tilts its head, cinematic close-up.",
      "reference_image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0.textToVideo": {
    "source": "fal/wan3p0-text-to-video",
    "payload": {
      "prompt": "A red panda walks slowly through a bamboo forest at sunrise, cinematic close-up.",
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0Prime.imageToVideo": {
    "source": "fal/wan3p0-prime-image-to-video",
    "payload": {
      "prompt": "The cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0Prime.referenceToVideo": {
    "source": "fal/wan3p0-prime-reference-to-video",
    "payload": {
      "prompt": "The cat in Image 1 blinks slowly and tilts its head, cinematic close-up.",
      "reference_image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST alibaba.wan3p0Prime.textToVideo": {
    "source": "fal/wan3p0-prime-text-to-video",
    "payload": {
      "prompt": "A red panda walks slowly through a bamboo forest at sunrise, cinematic close-up.",
      "resolution": "480p",
      "aspect_ratio": "1:1",
      "duration": 2,
      "audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.flux3.extendVideo": {
    "source": "fal/flux-3-extend-video",
    "payload": {
      "prompt": "The jump continues into a smooth landing",
      "video_url": "<inline video/mp4 data URL — replace with a real URL or upload>",
      "resolution": "720p",
      "duration": 5,
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.flux3.firstLastFrameToVideo": {
    "source": "fal/flux-3-first-last-frame-to-video",
    "payload": {
      "prompt": "A cat walks across the frame in one continuous shot",
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "end_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "720p",
      "duration": 5,
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.flux3.imageToVideo": {
    "source": "fal/flux-3-image-to-video",
    "payload": {
      "prompt": "The person turns toward the camera and smiles",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "720p",
      "duration": 5,
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.flux3.keyframesToVideo": {
    "source": "fal/flux-3-keyframes-to-video",
    "payload": {
      "prompt": "A person transforms into a cat in one continuous shot",
      "keyframes": [
        {
          "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
          "frame_index": 0
        },
        {
          "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
          "frame_index": 48
        },
        {
          "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
          "frame_index": 96
        }
      ],
      "resolution": "720p",
      "duration": 5,
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.flux3.textToVideo": {
    "source": "fal/flux-3-text-to-video",
    "payload": {
      "prompt": "A paper boat glides through a quiet rain puddle",
      "resolution": "720p",
      "duration": 5,
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST blackforestlabs.fluxVideoUpscale": {
    "source": "fal/flux-video-upscale",
    "payload": {
      "video_url": "<inline video/mp4 data URL — replace with a real URL or upload>",
      "upscale_factor": 1.5,
      "creativity": 0
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedSpeech.tts.v2": {
    "source": "fal/bytedance-seed-speech-tts-v2",
    "payload": {
      "text": "Hello from Apicity.",
      "voice": "stokie_en",
      "output_format": "mp3",
      "sample_rate": 24000,
      "speed": 1,
      "volume": 1,
      "pitch": 0,
      "language": "en",
      "voice_instruction": "Speak in a warm, cheerful tone."
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p0.fast.imageToVideo": {
    "source": "fal/bytedance-seedance2p0-fast-image-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p0.fast.textToVideo": {
    "source": "fal/bytedance-seedance2p0-fast-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p0.imageToVideo": {
    "source": "fal/bytedance-seedance2p0-image-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p0.textToVideo": {
    "source": "fal/bytedance-seedance2p0-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p5.imageToVideo": {
    "source": "fal/bytedance-seedance2p5-image-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p5.referenceToVideo": {
    "source": "fal/bytedance-seedance2p5-reference-to-video",
    "payload": {
      "prompt": "@Image1 follows the gentle head movement from @Video1, cinematic close-up.",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "video_urls": [
        "<inline video/mp4 data URL — replace with a real URL or upload>"
      ],
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedance2p5.textToVideo": {
    "source": "fal/bytedance-seedance2p5-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "resolution": "480p",
      "duration": "4",
      "aspect_ratio": "1:1",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedream.v5.lite.edit": {
    "source": "fal/bytedance-seedream-v5-lite-edit",
    "payload": {
      "prompt": "Change the background to a beautiful sunset beach scene with palm trees",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "num_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST bytedance.seedream.v5.lite.textToImage": {
    "source": "fal/bytedance-seedream-v5-lite-text-to-image",
    "payload": {
      "prompt": "A photorealistic red fox sitting in a snowy forest clearing at golden hour",
      "num_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST falAi.elevenlabs.speechToText.scribeV2": {
    "source": "fal/elevenlabs-speech-to-text-scribe-v2",
    "payload": {
      "audio_url": "https://storage.googleapis.com/falserverless/example_inputs/elevenlabs/scribe_v2_in.mp3",
      "language_code": "eng",
      "tag_audio_events": true,
      "diarize": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST geminiOmniFlash": {
    "source": "fal/google-gemini-omni-flash",
    "payload": {
      "prompt": "A calico cat naps on a sunlit windowsill, purring softly.",
      "duration": 3
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gptImage1p5": {
    "source": "fal/gpt-image-1.5",
    "payload": {
      "prompt": "An action shot of a black lab swimming in an inground suburban swimming pool.",
      "num_images": 1,
      "image_size": "1024x1024",
      "output_format": "png",
      "quality": "low"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST gptImage1p5.edit": {
    "source": "fal/gpt-image-1.5-edit",
    "payload": {
      "prompt": "place the man in a red mercedes convertible driving down the california coastline at sunset",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "num_images": 1,
      "quality": "low",
      "output_format": "png"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST hunyuan.v3.instructEdit": {
    "source": "fal/hunyuan-image-v3-instruct-edit",
    "payload": {
      "prompt": "Turn this cat into a watercolor painting",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "num_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.o3p4k.imageToVideo": {
    "source": "fal/kling-video-o3p4k-image-to-video",
    "payload": {
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "prompt": "the man waves at the camera as the wind blows his hair",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.o3p4k.referenceToVideo": {
    "source": "fal/kling-video-o3p4k-reference-to-video",
    "payload": {
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "prompt": "the man waves at the camera as the wind blows his hair",
      "duration": "5",
      "generate_audio": false,
      "aspect_ratio": "16:9"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.o3p4k.textToVideo": {
    "source": "fal/kling-video-o3p4k-text-to-video",
    "payload": {
      "prompt": "A mecha lands on the ground to save the city, and says \"I'm here\", in anime style",
      "aspect_ratio": "16:9",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.v3.pro.imageToVideo": {
    "source": "fal/kling-video-v3-pro-image-to-video",
    "payload": {
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "prompt": "the man waves at the camera as the wind blows his hair",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.v3.pro.textToVideo": {
    "source": "fal/kling-video-v3-pro-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "aspect_ratio": "1:1",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.v3.standard.imageToVideo": {
    "source": "fal/kling-video-v3-standard-image-to-video",
    "payload": {
      "start_image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "prompt": "the man waves at the camera as the wind blows his hair",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST klingVideo.v3.standard.textToVideo": {
    "source": "fal/kling-video-v3-standard-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "aspect_ratio": "1:1",
      "duration": "5",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana.edit": {
    "source": "fal/nano-banana-edit",
    "payload": {
      "prompt": "make a photo of the man driving a red mercedes convertible down the california coastline at sunset",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ]
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana.textToImage": {
    "source": "fal/nano-banana",
    "payload": {
      "prompt": "An action shot of a black lab swimming in an inground suburban swimming pool.",
      "num_images": 1,
      "aspect_ratio": "1:1",
      "output_format": "png",
      "safety_tolerance": "4"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana2.edit": {
    "source": "fal/nano-banana-2-edit",
    "payload": {
      "prompt": "make a photo of the man driving a red mercedes convertible down the california coastline at sunset",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ]
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana2.textToImage": {
    "source": "fal/nano-banana-2",
    "payload": {
      "prompt": "An action shot of a black lab swimming in an inground suburban swimming pool.",
      "num_images": 1,
      "aspect_ratio": "1:1",
      "output_format": "png",
      "safety_tolerance": "4",
      "resolution": "1K"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana2Lite.edit": {
    "source": "fal/nano-banana-2-lite-edit",
    "payload": {
      "prompt": "Turn this portrait into a polished studio editorial image with a muted teal backdrop, preserving the person.",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "num_images": 1,
      "aspect_ratio": "1:1",
      "output_format": "png",
      "safety_tolerance": "4",
      "limit_generations": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBanana2Lite.textToImage": {
    "source": "fal/nano-banana-2-lite",
    "payload": {
      "prompt": "A clean editorial product photo of a small brass desk lamp on a walnut table, soft morning window light, no text.",
      "num_images": 1,
      "aspect_ratio": "1:1",
      "output_format": "png",
      "safety_tolerance": "4",
      "limit_generations": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBananaPro.edit": {
    "source": "fal/nano-banana-pro-edit",
    "payload": {
      "prompt": "make a photo of the man driving a red mercedes convertible down the california coastline at sunset",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ]
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST nanoBananaPro.textToImage": {
    "source": "fal/nano-banana-pro",
    "payload": {
      "prompt": "An action shot of a black lab swimming in an inground suburban swimming pool.",
      "num_images": 1,
      "aspect_ratio": "1:1",
      "output_format": "png",
      "safety_tolerance": "4",
      "resolution": "1K"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST qwenImage": {
    "source": "fal/qwen-image",
    "payload": {
      "prompt": "An action shot of a black lab swimming in an inground suburban swimming pool.",
      "num_images": 1,
      "image_size": "square_hd",
      "output_format": "png",
      "num_inference_steps": 30
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST qwenImage.edit": {
    "source": "fal/qwen-image-edit",
    "payload": {
      "prompt": "change the background to a red mercedes convertible on the california coastline at sunset",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "num_images": 1
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST sora2.imageToVideo": {
    "source": "fal/sora-2-image-to-video",
    "payload": {
      "prompt": "the man waves at the camera as the wind blows his hair",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "aspect_ratio": "16:9",
      "duration": 4
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST sora2.textToVideo": {
    "source": "fal/sora-2",
    "payload": {
      "prompt": "A black lab swimming in an inground suburban swimming pool at sunset.",
      "aspect_ratio": "16:9",
      "duration": 4
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST storage.upload.initiate": {
    "source": "fal/storage-upload-initiate",
    "payload": {
      "file_name": "cat1.jpg",
      "content_type": "image/jpeg"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST v1.models.pricing.estimate": {
    "source": "fal/estimate-cost",
    "payload": {
      "estimate_type": "unit_price",
      "endpoints": {
        "fal-ai/flux/dev": {
          "unit_quantity": 100
        }
      }
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST veo3p1.imageToVideo": {
    "source": "fal/veo3-1-image-to-video",
    "payload": {
      "prompt": "the man waves at the camera as the wind blows his hair",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "aspect_ratio": "16:9",
      "duration": "4s",
      "resolution": "720p",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST veo3p1.textToVideo": {
    "source": "fal/veo3-1",
    "payload": {
      "prompt": "A black lab swimming in an inground suburban swimming pool at sunset.",
      "aspect_ratio": "16:9",
      "duration": "4s",
      "resolution": "720p",
      "generate_audio": false
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST virtualTryOn": {
    "source": "fal/google-virtual-try-on",
    "payload": {
      "person_image_url": "https://storage.googleapis.com/falserverless/model_tests/leffa/person_image.jpg",
      "product_image_url": "https://storage.googleapis.com/falserverless/model_tests/leffa/tshirt_image.jpg",
      "num_images": 1
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.edit": {
    "source": "fal/wan-v2p7-edit",
    "payload": {
      "prompt": "Turn image 1 into a watercolor painting.",
      "image_urls": [
        "https://storage.googleapis.com/falserverless/model_tests/wan/dragon-warrior.jpg"
      ],
      "num_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.imageToVideo": {
    "source": "fal/wan-v2p7-image-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "resolution": "720p",
      "duration": 2
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.pro.edit": {
    "source": "fal/wan-v2p7-pro-edit",
    "payload": {
      "prompt": "Turn image 1 into a watercolor painting.",
      "image_urls": [
        "https://storage.googleapis.com/falserverless/model_tests/wan/dragon-warrior.jpg"
      ],
      "num_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.pro.textToImage": {
    "source": "fal/wan-v2p7-pro-text-to-image",
    "payload": {
      "prompt": "An astronaut riding a horse in a photorealistic style.",
      "max_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.textToImage": {
    "source": "fal/wan-v2p7-text-to-image",
    "payload": {
      "prompt": "An astronaut riding a horse in a photorealistic style.",
      "max_images": 1,
      "enable_safety_checker": true
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST wan.v2p7.textToVideo": {
    "source": "fal/wan-v2p7-text-to-video",
    "payload": {
      "prompt": "A white odd-eyed cat blinks slowly and tilts its head, soft breeze through fur, cinematic close-up.",
      "resolution": "720p",
      "duration": 2,
      "aspect_ratio": "1:1"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineImage": {
    "source": "fal/xai-grok-imagine-image",
    "payload": {
      "prompt": "Abstract human silhouette, golden particles ready to burst outward representing joy, data visualization style, emotional expression through particles, artistic scientific",
      "num_images": 1,
      "aspect_ratio": "1:1",
      "resolution": "1k",
      "output_format": "jpeg"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineImage.edit": {
    "source": "fal/xai-grok-imagine-image-edit",
    "payload": {
      "prompt": "Make this scene more realistic but still keep the game vibes",
      "num_images": 1,
      "resolution": "1k",
      "output_format": "jpeg",
      "image_urls": [
        "https://v3b.fal.media/files/b/0a8b911d/Abk8vStrvmSPlzUqI_NN3_image_043.png"
      ]
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineImage.v2p0.edit": {
    "source": "fal/xai-grok-imagine-image-v2p0-edit",
    "payload": {
      "prompt": "Turn this cat into a watercolor painting.",
      "image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ]
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineImage.v2p0.textToImage": {
    "source": "fal/xai-grok-imagine-image-v2p0-text-to-image",
    "payload": {
      "prompt": "A serene mountain landscape at sunrise."
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineVideo.editVideo": {
    "source": "fal/xai-grok-imagine-video-edit-video",
    "payload": {
      "prompt": "Colorize the video with warm sunset tones",
      "video_url": "<inline video/mp4 data URL — replace with a real URL or upload>",
      "resolution": "480p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineVideo.extendVideo": {
    "source": "fal/xai-grok-imagine-video-extend-video",
    "payload": {
      "prompt": "The camera slowly zooms out to reveal the city skyline at sunset",
      "video_url": "<inline video/mp4 data URL — replace with a real URL or upload>",
      "duration": 4
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineVideo.imageToVideo": {
    "source": "fal/xai-grok-imagine-video-image-to-video",
    "payload": {
      "prompt": "the man waves at the camera as the wind blows his hair",
      "image_url": "<inline image/jpeg data URL — replace with a real URL or upload>",
      "duration": 6,
      "aspect_ratio": "16:9",
      "resolution": "720p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  },
  "POST xai.grokImagineVideo.referenceToVideo": {
    "source": "fal/xai-grok-imagine-video-reference-to-video",
    "payload": {
      "prompt": "A @Image1 walking through a sunlit meadow, cinematic slow motion",
      "reference_image_urls": [
        "<inline image/jpeg data URL — replace with a real URL or upload>"
      ],
      "duration": 6,
      "aspect_ratio": "16:9",
      "resolution": "480p"
    },
    "tier": "prohibitive",
    "runByDefault": false
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
