// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET v1.batches": {
    "source": "openai/batches-list-limit",
    "payload": {
      "limit": 2
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "GET v1.chat.completions": {
    "source": "openai/stored-completions-list-limit",
    "payload": {
      "limit": 1
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "GET v1.fineTuning.jobs": {
    "source": "openai/fine-tuning-jobs-list",
    "payload": {
      "limit": 5
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "GET v1.vectorStores": {
    "source": "openai/vector-stores-read",
    "payload": {
      "limit": 2,
      "order": "desc"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.audio.speech": {
    "source": "openai/speech-hello",
    "payload": {
      "model": "tts-1",
      "input": "Hello, world!",
      "voice": "alloy",
      "response_format": "mp3"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.chat.completions": {
    "source": "openai/chat-hello",
    "payload": {
      "model": "gpt-5.4-2026-03-05",
      "messages": [
        {
          "role": "user",
          "content": "Say hello in one sentence."
        }
      ],
      "temperature": 0
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.completions": {
    "source": "openai/completions-hello",
    "payload": {
      "model": "gpt-3.5-turbo-instruct",
      "prompt": "Say this is a test",
      "max_tokens": 7,
      "temperature": 0
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.containers": {
    "source": "openai/containers-create",
    "payload": {
      "name": "apicity-container-create-test",
      "expires_after": {
        "anchor": "last_active_at",
        "minutes": 20
      },
      "memory_limit": "1g",
      "network_policy": {
        "type": "disabled"
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.conversations": {
    "source": "openai/conversations-create",
    "payload": {
      "items": [
        {
          "role": "user",
          "content": "Hello, let's start a conversation."
        }
      ],
      "metadata": {
        "topic": "greeting"
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.embeddings": {
    "source": "openai/embeddings-hello",
    "payload": {
      "model": "text-embedding-3-small",
      "input": "Hello world"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.evals": {
    "source": "openai/evals-create",
    "payload": {
      "name": "Apicity support ticket fixture",
      "data_source_config": {
        "type": "custom",
        "item_schema": {
          "type": "object",
          "properties": {
            "ticket": {
              "type": "string"
            },
            "category": {
              "type": "string"
            }
          },
          "required": [
            "ticket",
            "category"
          ]
        },
        "include_sample_schema": true
      },
      "testing_criteria": [
        {
          "type": "string_check",
          "name": "Category string match",
          "input": "{{ sample.output_text }}",
          "operation": "eq",
          "reference": "{{ item.category }}"
        }
      ],
      "metadata": {
        "source": "apicity"
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.images.generations": {
    "source": "openai/images-generations",
    "payload": {
      "prompt": "A white siamese cat",
      "model": "dall-e-2",
      "n": 1,
      "size": "256x256"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.moderations": {
    "source": "openai/moderations-hello",
    "payload": {
      "input": "The weather is nice today.",
      "model": "omni-moderation-latest"
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.realtime.clientSecrets": {
    "source": "openai/realtime-client-secrets",
    "payload": {
      "expires_after": {
        "anchor": "created_at",
        "seconds": 600
      },
      "session": {
        "type": "realtime",
        "model": "gpt-realtime",
        "instructions": "You are a concise test assistant."
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.responses": {
    "source": "openai/responses-hello",
    "payload": {
      "model": "gpt-4o-mini",
      "input": "Say hello in one sentence.",
      "temperature": 0,
      "max_output_tokens": 100
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.responses.inputTokens": {
    "source": "openai/responses-input-tokens",
    "payload": {
      "model": "gpt-4o-mini",
      "input": "Say hello in one sentence."
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.uploads": {
    "source": "openai/uploads-create",
    "payload": {
      "purpose": "fine-tune",
      "filename": "apicity-upload-create.jsonl",
      "bytes": 18,
      "mime_type": "application/jsonl",
      "expires_after": {
        "anchor": "created_at",
        "seconds": 3600
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.vectorStores": {
    "source": "openai/vector-stores-read",
    "payload": {
      "name": "Apicity vector store read test",
      "expires_after": {
        "anchor": "last_active_at",
        "days": 1
      },
      "metadata": {
        "purpose": "integration-test"
      }
    },
    "tier": "expensive",
    "runByDefault": false
  },
  "POST v1.vectorStores.search": {
    "source": "openai/vector-stores-search",
    "payload": {
      "query": "return policy",
      "max_num_results": 5
    },
    "tier": "expensive",
    "runByDefault": false
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
