// Auto-generated by `pnpm run gen:examples` — do not edit by hand.
// Source: tests/recordings/<provider>_*/<test>_*/recording.har
//
// Each entry is the green-path payload for one endpoint, mined from a real
// integration-test recording. `attachExamples` walks the provider tree and
// hangs the matching entry off each endpoint function as `.example`.

export interface EndpointExample {
  source: string;
  payload: unknown;
  /** Canonical cost tier of this endpoint (see @apicity/cost). */
  tier: "cheap" | "expensive" | "prohibitive";
  /** Whether an example runner may execute this by default (cheap only). */
  runByDefault: boolean;
}

const EXAMPLES: Record<string, EndpointExample> = {
  "GET api.v3.aggTrades": {
    "source": "binance/agg-trades",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.avgPrice": {
    "source": "binance/avg-price",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.depth": {
    "source": "binance/depth",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.exchangeInfo": {
    "source": "binance/exchange-info",
    "payload": {
      "symbol": "BTCUSDT",
      "showPermissionSets": false
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.executionRules": {
    "source": "binance/execution-rules",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.historicalBlockTrades": {
    "source": "binance/historical-block-trades",
    "payload": {
      "symbol": "BTCUSDT",
      "fromId": 1,
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.historicalTrades": {
    "source": "binance/historical-trades",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.klines": {
    "source": "binance/klines",
    "payload": {
      "symbol": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.referencePrice": {
    "source": "binance/reference-price",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.referencePrice.calculation": {
    "source": "binance/reference-price-calculation",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.ticker": {
    "source": "binance/ticker",
    "payload": {
      "symbol": "BTCUSDT",
      "windowSize": "1d"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.ticker.bookTicker": {
    "source": "binance/ticker-book-ticker",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.ticker.price": {
    "source": "binance/ticker-price",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.ticker.tradingDay": {
    "source": "binance/ticker-trading-day",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.ticker.twentyFourHr": {
    "source": "binance/ticker-24hr",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.trades": {
    "source": "binance/trades",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET api.v3.uiKlines": {
    "source": "binance/ui-klines",
    "payload": {
      "symbol": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.basis": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "contractType": "PERPETUAL",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.deliveryPrice": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.globalLongShortAccountRatio": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.openInterestHist": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "contractType": "PERPETUAL",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.takerBuySellVol": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "contractType": "PERPETUAL",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.topLongShortAccountRatio": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET coinMFutures.data.topLongShortPositionRatio": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.aggTrades": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.constituents": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.continuousKlines": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "contractType": "PERPETUAL",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.depth": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.fundingRate": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.indexPriceKlines": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "pair": "BTCUSD",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.klines": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.markPriceKlines": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.openInterest": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.premiumIndex": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.premiumIndexKlines": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.ticker.bookTicker": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.ticker.price": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.ticker.twentyFourHr": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET dapi.v1.trades": {
    "source": "binance/coin-m-market-data",
    "payload": {
      "symbol": "BTCUSD_PERP",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.blockTrades": {
    "source": "binance/options-market-data",
    "payload": {
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.depth": {
    "source": "binance/options-market-data",
    "payload": {
      "symbol": "BTC-260626-140000-C",
      "limit": 10
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.exerciseHistory": {
    "source": "binance/options-market-data",
    "payload": {
      "underlying": "BTCUSDT",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.index": {
    "source": "binance/options-market-data",
    "payload": {
      "underlying": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.klines": {
    "source": "binance/options-market-data",
    "payload": {
      "symbol": "BTC-260626-140000-C",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.mark": {
    "source": "binance/options-market-data",
    "payload": {
      "symbol": "BTC-260626-140000-C"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.openInterest": {
    "source": "binance/options-market-data",
    "payload": {
      "underlyingAsset": "BTC",
      "expiration": 260626
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.ticker": {
    "source": "binance/options-market-data",
    "payload": {
      "symbol": "BTC-260626-140000-C"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET eapi.v1.trades": {
    "source": "binance/options-market-data",
    "payload": {
      "symbol": "BTC-260626-140000-C",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.aggTrades": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.assetIndex": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "USDTUSD"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.constituents": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.continuousKlines": {
    "source": "binance/fapi-market-data",
    "payload": {
      "pair": "BTCUSDT",
      "contractType": "PERPETUAL",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.depth": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 5
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.fundingRate": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.indexPriceKlines": {
    "source": "binance/fapi-market-data",
    "payload": {
      "pair": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.insuranceBalance": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.klines": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.markPriceKlines": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.openInterest": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.premiumIndex": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.premiumIndexKlines": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "interval": "1m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.rpiDepth": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.symbolAdlRisk": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.ticker.bookTicker": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.ticker.twentyFourHr": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v1.trades": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET fapi.v2.ticker.price": {
    "source": "binance/fapi-market-data",
    "payload": {
      "symbol": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.basis": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "pair": "BTCUSDT",
      "contractType": "PERPETUAL",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.deliveryPrice": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "pair": "BTCUSDT"
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.globalLongShortAccountRatio": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.openInterestHist": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.takerlongshortRatio": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.topLongShortAccountRatio": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  },
  "GET futures.data.topLongShortPositionRatio": {
    "source": "binance/futures-data-market-data",
    "payload": {
      "symbol": "BTCUSDT",
      "period": "5m",
      "limit": 1
    },
    "tier": "cheap",
    "runByDefault": true
  }
};

export default EXAMPLES;

// Walks each "<METHOD> <dotPath>" key onto the provider's tree. Tries the
// standard `provider.<method>.<dotPath>` shape first, then a few fallbacks
// to cover providers with non-standard layouts (fal's `.run.` namespace,
// kie's sub-providers, `free`'s flat root). Returns the same provider for
// drop-in use as `return attachExamples({ ... });`.
export function attachExamples<T>(provider: T): T {
  const root = provider as Record<string, unknown>;
  const HTTP_KEYS = new Set(["post", "get", "put", "delete", "patch", "head"]);
  for (const [key, example] of Object.entries(EXAMPLES)) {
    const sp = key.indexOf(" ");
    if (sp < 0) continue;
    const method = key.slice(0, sp).toLowerCase();
    const segs = key.slice(sp + 1).split(".");
    const candidates: Array<unknown> = [
      root[method],
      (root[method] as Record<string, unknown> | undefined)?.run,
      root,
    ];
    if (segs.length > 1) {
      const sub = root[segs[0]];
      if (sub && typeof sub === "object") {
        const subMethod = (sub as Record<string, unknown>)[method];
        if (subMethod) candidates.push({ __nested: subMethod, __segs: segs.slice(1) });
      }
    }
    let attached = false;
    for (const c of candidates) {
      const fn = walkToFn(c, segs);
      if (fn) {
        Object.assign(fn, { example });
        attached = true;
        break;
      }
    }
    if (attached) continue;
    for (const k of Object.keys(root)) {
      if (HTTP_KEYS.has(k)) continue;
      if (!segs.includes(k)) continue;
      const sub = root[k];
      if (!sub || typeof sub !== "object") continue;
      const subMethod = (sub as Record<string, unknown>)[method];
      if (!subMethod) continue;
      const fn = walkToFn(subMethod, segs);
      if (fn) {
        Object.assign(fn, { example });
        break;
      }
    }
  }
  return provider;
}

function walkToFn(start: unknown, segs: string[]): ((...args: unknown[]) => unknown) | null {
  if (start && typeof start === "object" && "__nested" in (start as object)) {
    const wrapper = start as { __nested: unknown; __segs: string[] };
    return walkToFn(wrapper.__nested, wrapper.__segs);
  }
  let cur: unknown = start;
  for (const seg of segs) {
    if (cur === null || cur === undefined) return null;
    const t = typeof cur;
    if (t !== "object" && t !== "function") return null;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return typeof cur === "function"
    ? (cur as (...args: unknown[]) => unknown)
    : null;
}
