import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { DoltHubOptionsSchema } from "@apicity/dolthub";

// Drift guard: the dolthub README is generated by scripts/doc-gen.mjs, and
// its createDoltHub examples must only use options the package actually
// reads (the DoltHubOptionsSchema contract, e.g. apiToken — not apiKey).
const readmePath = resolve(
  __dirname,
  "../../packages/provider/dolthub/README.md"
);

function extractCreateDoltHubOptionKeys(readme: string): string[][] {
  const calls = readme.match(/createDoltHub\(\{[\s\S]*?\}\)/g) ?? [];
  return calls.map((call) => {
    const body = call.slice(call.indexOf("{") + 1, call.lastIndexOf("}"));
    return [...body.matchAll(/([A-Za-z_$][\w$]*)\s*:/g)].map((m) => m[1]);
  });
}

describe("dolthub README createDoltHub examples", () => {
  const readme = readFileSync(readmePath, "utf-8");
  const examples = extractCreateDoltHubOptionKeys(readme);

  it("includes at least one createDoltHub example", () => {
    expect(examples.length).toBeGreaterThan(0);
  });

  it("only uses options present in DoltHubOptionsSchema", () => {
    const allowed = new Set(Object.keys(DoltHubOptionsSchema.shape));
    const unknown = examples.flat().filter((key) => !allowed.has(key));
    expect(unknown).toEqual([]);
  });

  it("passes the apiToken auth option", () => {
    expect(examples.some((keys) => keys.includes("apiToken"))).toBe(true);
  });
});
